### ISSUE TITLE
Using FILTER_SANITIZE_EMAIL with auth

### ISSUE THREAD

**Issue by Abraham-Tourdex** [delight-im/PHP-Auth#105]
Looking at the code in UserManager, I see there is no call to FILTER_SANITIZE_EMAIL. I guess we should be sanitizing our usernames and emails _before_ passing them to `$auth`?

**Comment by ocram** [comment]
No, you don’t need to do that.

While this library does not use `FILTER_SANITIZE_EMAIL`, it *does* use [`FILTER_VALIDATE_EMAIL`](https://github.com/delight-im/PHP-Auth/blob/7a8508d56e8bb785139eb92ae3aa6b61bc210bbf/src/UserManager.php#L296). Apart from that, there would have been other ways to validate the syntax of email addresses, using neither of those flags.

More importantly, this library lets you do *actual* verification of email addresses by sending confirmation links to those addresses. This is highly recommended. Without this, you only know whether the the addresses’ syntax is correct or not.

Regarding usernames, I don’t see how these are related. You need to sanitize them only if you have custom rules that require you to do so, e.g. that you don’t allow `admin` or the name of your site as usernames or that you don’t allow numbers in usernames.
