### ISSUE TITLE
Accessing email variable from register() callback

### ISSUE THREAD

**Issue by Abraham-Tourdex** [delight-im/PHP-Auth#107]
Hi there, I might be totally confused but I have been having issues accessing variables within the scope of the email verify callback fired from `register()` .

When building the verify URL within the callback I cannot access that variable outside the callback. When emailing from within the callback I cannot access the `$email` variable that is passed to the `register()` function.

I am using PHPMailer to handle my emailing and there might be some kind of conflict there as it navigates SMTP servers etc.

In order to hack around the scope I simply edited the register function in `UserManager.php` to pass the `$email` parameter through to the callback, and then used that in my callback code. It's probably my lack of understanding leading to this issue but PHPMailer takes a while to process its mail function and I'm assuming that the timing there is messing with the callback order, here's my code as working with the callback hack:

	$userId = $auth->register( $email, $pword, null, function ($selector, $token, $email) {
	
		// send `$selector` and `$token` to the user (e.g. via email)
		$url = 'http://www.example.com?selector=' . \urlencode($selector) . '&token=' . \urlencode($token);
	
		$mail = new PHPMailer(true);
		//Server settings
		$mail->SMTPDebug = 2;
		$mail->isSMTP();
		$mail->Host = 'snip'; 
		$mail->SMTPAuth = true;
		$mail->Username = 'snip';
		$mail->Password = 'snip';
		$mail->SMTPSecure = 'tls';
		$mail->Port = 587;
	
		//Recipients
		$mail->setFrom('snip');
		$mail->addAddress($email);
	
		//Content
		$mail->isHTML(true);
		$mail->Subject = 'Subject';
		$mail->Body    =  $url;
	
		$mail->send();
	});

Any advice?

**Comment by ocram** [comment]
Don’t worry, questions are part of what this issue tracker is for.

The callback function in question, like all the other callback functions for email verification in this library, is a [closure](http://php.net/manual/en/functions.anonymous.php). In PHP, this simply means that, apart from its parameters and [superglobals](http://php.net/manual/en/language.variables.superglobals.php), you need to add a `use` clause to make variables from the parent scope available.

This has also been added to the documentation now: https://github.com/delight-im/PHP-Auth/commit/c685f229378fa8b83942afce0e4ec830abcd5e1b

Does that help?

**Comment by Abraham-Tourdex** [comment]
Very much so, thanks!
