### ISSUE TITLE
Token Auth

### ISSUE THREAD

**Issue by stipic** [delight-im/PHP-Auth#114]
Hello,

I'm working on mobile apps, I need to authenticate users through token

is there a way?

**Comment by ocram** [comment]
You can certainly use cookie-based authentication, even for mobile apps. But, of course, a token-based approach without cookies is often preferred (especially for REST).

Unfortunately, there’s nothing included yet in that regard. Sorry!

By the way, https://github.com/delight-im/PHP-Auth/issues/76 and https://github.com/delight-im/PHP-Auth/issues/96 are somewhat related.
