### ISSUE TITLE
Something goofy with charset

### ISSUE THREAD

**Issue by MB34** [delight-im/PHP-Auth#116]
I am using this code with PGSql driver:

    $dataSource->setCharset('UTF8');

Yet, I'm getting this message:
`Fatal error: Uncaught Delight\Auth\DatabaseError: SQLSTATE[08006] [7] invalid connection option "charset" in C:\wamp\www\ypl\vendor\delight-im\auth\src\Auth.php on line 1699`

If I leave out the `setCharset()`, still get the message. I have checked and yes, `SHOW SERVER_ENCODING` returns `UTF8`

`composer show delight-im/Auth` returns version 8.02. How do I know what version my schema is? I downloaded the latest from Github and see no difference in the SQL code.

**Comment by ocram** [comment]
Thanks a lot for reporting this, and for checking that you’re using the latest version (which you are) and that you’re using the latest schema as well (which you seem to be)!

The reason you see no difference when removing the call to the mutator method `setCharset` is that `UTF8` is also used as a default for PostgreSQL by our [database library](https://github.com/delight-im/PHP-DB).

So you’d need to set the charset to `null` explicitly. Can you try this? Does that help?

Apart from that easy fix, it would be great if you could help us implement a real fix [here](https://github.com/delight-im/PHP-DB/issues/10).

**Comment by MB34** [comment]
No, still displayed the error if setting explicitly to `null`.

**Comment by ocram** [comment]
Oh well, the charset is always cast to a string, so all you can get is an empty string, which will still produce the error. Can you try the other fix, referenced in the linked issue?

**Comment by MB34** [comment]
Will continue comments in linked issue.

**Comment by ocram** [comment]
This has now been fixed upstream in the database library. Updating `delight-im/db` to version 1.2.1 or later via Composer should be sufficient to get rid of this problem.
