### ISSUE TITLE
If user not logged in, getRoles() returns roles.

### ISSUE THREAD

**Issue by MB34** [delight-im/PHP-Auth#118]
If I pass invalid credentials to `$auth->login()` and then immediately attempt to get the userID 
`$auth->GetUserId()`, it returns nothing. Then when I call `$auth->getRoles()`, it returns the role for the only user in my `users` table.

Is this expected behavior?

**Code:**

    $auth = new \Delight\Auth\Auth($db);
    $userId = null;
    $msg = '';

    try {
        $auth->login($_REQUEST['email'], $_REQUEST['password']);
        $userId = $auth->getUserId();
    }
    catch (\Delight\Auth\InvalidEmailException $e) {
        $msg .= 'wrong email address';
    }
    catch (\Delight\Auth\InvalidPasswordException $e) {
        $msg .= 'wrong password';
    }
    catch (\Delight\Auth\EmailNotVerifiedException $e) {
        $msg .= 'email not verified';
    }
    catch (\Delight\Auth\TooManyRequestsException $e) {
        $msg .= 'too many requests';
    }

    try {
        $auth->admin()->addRoleForUserById($userId, \Delight\Auth\Role::ADMIN);
    }
    catch (\Delight\Auth\UnknownIdException $e) {
        $msg .= 'unknown user ID';
    }

    $authorized = $auth->hasRole(\Delight\Auth\Role::ADMIN);

    echo "" ."\r\n";

**Results:**

**Comment by frankieeedeee** [comment]
Hey again!

Well first of all, if you pass invalid credentials to `$auth->login($_REQUEST['email'], $_REQUEST['password']);` your `$userId = $auth->getUserId();` won't get called, so in your case the value of `$userID` remains `null` - So be careful with that next try/catch block, you'll be calling `addRoleForUserById($userId, \Delight\Auth\Role::ADMIN);` with $userID as `NULL`

Regarding why `$auth->getRoles()` is producing the `ADMIN` role, this I believe would be as a result of you previously assigning the role to the currently logged in user **before** you attempted to pass invalid login information to `$auth->login()`, and I can only assume that you haven't performed the `$auth->logout()` operation in-between. Thus, there is a user still logged into your session, and that role is stored within the session data. So, create a logout script that you can run to logout the user and clear any remaining session data, and let me know if there is a different result.

Be aware also that, from the ReadMe, 

> Changes to a user’s set of roles take effect in the local session immediately, as expected. In other sessions (e.g. on other devices), the changes may need up to five minutes to take effect, though.

Hope it helps!

**Comment by MB34** [comment]
Gotcha, I forgot that it is using sessions and I need to logout the current user. You are right about getting the userID, too. Guess I need to learn to walk before trying to fly.

**Comment by frankieeedeee** [comment]
All good! :))

**Comment by ocram** [comment]
@frankieeedeee Really appreciate your help – thank you very much!

@MB34 It was good to ask this, because such things affect other developers, who will later find this thread very helpful, more often than one might think. By the way, this library working with sessions is why you can also move parts of your code to other files. You don’t have to execute all that code after *every* login and the user will remain logged in while browsing between different files.
