### ISSUE TITLE
Log in with username

### ISSUE THREAD

**Issue by ocram** [delight-im/PHP-Auth#12]
> For example, if I want a login method with user name instead of e-mail.
>
> @sportfogadas in https://github.com/delight-im/PHP-Auth/issues/11

**Comment by ocram** [comment]
You can't just provide a login with usernames as they are stored currently. The reason is that usernames are (intentionally) not required to be unique. The unique identifier with this library is the email address.

We didn't want to require usernames to be unique as well, since usernames could also be used as display names or nicknames that don't need to be unique.

But there's definitely something we could do in order to provide that feature nonetheless:

We could add an additional method named `registerWithUniqueUsername` that, as the name suggests, ensures that the username that you sign up with is always unique.

Having added that new safeguard then, we could add another new method named `loginWithUsername` that does just what you want. Of course, if there were two accounts with the same username, e.g. because you forgot to use `registerWithUniqueUsername` once and used the simple `register` instead, it would throw an exception.

What do you think?

**Comment by sportfogadas** [comment]
That can be an option of course, but wouldn't it be simpler to simply make the username column unique in the database? I didn't check all the code but I could see there was an IntegrityConstraintViolationException caught at insert, that could just as well work in case of unique usernames. Of course, if you do this and somebody upgrades their older library, it will break it.

That's why I think extending it if you want something done differently is a better option. I did change all private methods to protected in my own downloaded version and extended it overriding the login method and extending it with a couple of new ones. For example I needed a special add function that didn't have throttling (importing an existing user database). This way all this can be done with ease. It's just an idea.

**Comment by ocram** [comment]
> but wouldn't it be simpler to simply make the username column unique in the database? I didn't check all the code but I could see there was an IntegrityConstraintViolationException caught at insert, that could just as well work in case of unique usernames.

That's correct, well spotted! Your solution would work, but it's just not that portable and maintainable.

> For example I needed a special add function that didn't have throttling (importing an existing user database).

Another great use case for additional methods that need to be added. Thank you!

I agree that there are several methods that need to be added in the future, e.g. logging in with username and creating accounts without throttling, which you mentioned. But as I said, changing the database structure as needed or opening up everything for inheritance are just not the most elegant solutions.

For the login with username, I had already proposed a solution above.

Regarding the new feature of adding (multiple) accounts without throttling, I think that could be part of an administration suite. Why not let a new `$auth->admin()` expose an administration interface that allows for accounts to be created, viewed or deleted? We could add this to this library, freeing everyone from the need to add those features themselves through inheritance.

**Comment by sportfogadas** [comment]
Surely there are many possible solutions to one problem. Maybe the whole admin part should be separated into a different class and Auth should only handle the public side (login, registration, password change etc). These are just some random thoughts. What I like about this class is that it's lightweight and simple. For me it was a great starting point on which to build. Other will have different needs.

**Comment by ocram** [comment]
> Maybe the whole admin part should be separated into a different class and Auth should only handle the public side (login, registration, password change etc).

Absolutely agree! The accessor `$auth->admin()` was meant to return an instance of that new `Administration` class where methods such as `$auth->admin()->createUser(...)` or `$auth->admin()->deleteUser(...)` will be available.

> What I like about this class is that it's lightweight and simple.

It's really meant to stay that simple and lightweight. With a proper design, this is possible.

> For me it was a great starting point on which to build. Other will have different needs.

Well, that's certainly right, but the ultimate goal of this library is to unify all features and abstractions that most people need, so that (almost) nobody has to do the work of extending the feature set (which you just have done). It can save everybody some effort and time.

Let's leave this issue here open. At least the two features of logging in with one's username and creating users as an administrator will definitely be added.

**Comment by ocram** [comment]
The new `registerWithUniqueUsername` method has been added in https://github.com/delight-im/PHP-Auth/commit/dac2850aba8126e8594bff609dda029e8c8fe4c3, as a first step.

**Comment by ocram** [comment]
... and the new method `loginWithUsername` is now available as well: https://github.com/delight-im/PHP-Auth/commit/3cb2284870acf83e374f32c5358ad3c31c84ed9c

Throttling can practically be disabled by calling `setThrottlingOptions` as documented [here](https://github.com/delight-im/PHP-Auth/blob/8acd3a97791270bb931bd0bdb6e95e1d9df6f6b2/src/Auth.php#L1393). Nevertheless, the new administration interface described above will be added as well.
