### ISSUE TITLE
What happens when the cookie expires?

### ISSUE THREAD

**Issue by mmiraglia** [delight-im/PHP-Auth#121]
Hello everyone!
I have been testing the library and I can not tell what happens with the registry in the users_remembered table once the "remember me" cookie expires for the user.
The record is deleted at some point?
Thank you!!

**Comment by ocram** [comment]
Thanks!

You control the lifetime of the “remember me” cookie yourself, as described in the “Keeping the user logged in” section of the README. Apart from that, there’s also the normal session cookie, of course.

As for the entries in the database table, those just remain there right now. This is being discussed in https://github.com/delight-im/PHP-Auth/issues/68. If you need to fix this urgently, you can easily implement a quick solution yourself.

Does that help?

**Comment by mmiraglia** [comment]
Thx ocram!!
I searched for words like "delete" and "purge", it did not occur to me as "garbage collection" 🤣 
It is not urgent! I even thought about adding the delete of the expired records in a weekly or monthly maintenance cron. But I did not want to implement something that was already done and I have not seen it ...
Thanks again!!

**Comment by ocram** [comment]
Purging obsolete records with a weekly or monthly cron is absolutely fine. You can safely implement that. And when it’s implemented here as well, there won’t be any conflicts, either.
