### ISSUE TITLE
Feature Request: Return user_id on successful email verification

### ISSUE THREAD

**Issue by frankieeedeee** [delight-im/PHP-Auth#124]
Hey there,

Don't know if this is in the works yet, but due to the fact that a use case of mine involves tracking user data in parrallel with the Auth DB, it might be a good idea to return the `user_id` or `email` on successful email verification. That way, if someone is tracking user state alongside this library, we can update internal user state/log respective to the user that has just verified, ie:

```
try {
    $auth->confirmEmail($_GET['selector'], $_GET['token']);

    // email address has been verified
} catch (...
```

would become

```
try {
    $user_id = $auth->confirmEmail($_GET['selector'], $_GET['token']);

    // email address has been verified
} catch (...
```

and now internally, someone can call `$myAppUserModel->setStatus($user_id, "verified")`

Just a thought!

Cheers :)

**Comment by frankieeedeee** [comment]
Sorry my bad, I just had a look through src and found that this method does infact return the old email address (if any) and the most current email address in an array indexed at `0` and `1` respectively - Maybe we should note this in the docs? :))

**Comment by frankieeedeee** [comment]
If all good, have noted in #125 :))

**Comment by ocram** [comment]
Good point, thank you very much!

Also appreciate you digging into the code and finding the solution yourself, as well as submitting a potential patch. That’s great!

Updated in https://github.com/delight-im/PHP-Auth/commit/3120e3a6a5cef0271d826b3281d7f3d9d3277818.
