### ISSUE TITLE
google+ api compatibility

### ISSUE THREAD

**Issue by mdehghani65** [delight-im/PHP-Auth#129]
hi. the library is wonderful. i was wondering how i could use google auth api along with this library. how to store values ? wether inside the default tables or outside. the main problem i guess is that google api doesnt return a password. i wish there were methods implemented to handle the case and register google users in such a way that the info can be utilised.

**Comment by mdehghani65** [comment]
thx for your kind response and sorry for misspelling. yes you are completely right. so far i've managed to trigger google sign in ,fetch google user-info,check if user's email exist in db, in any case create login session, if the user email is new, then i generate a random password, make a new user record using $auth->register($email_from_google, $random_password, null). i mail the password to the user and let the user know he/she can also login using this credentials as alternative. after that i add additional google user-info by updating the user row in db. so now the user is part our users table but with more info. i guess the only problem is that the user is recognized by unique email while google recommends differentiating users by unique google id because it might happen that they change their email address.

**Comment by ocram** [comment]
Thanks, that makes sense.

Could you perhaps associate Google accounts and your internal accounts by storing the mappings between your user IDs and Google’s IDs (or ID Tokens) in a separate custom table?

**Comment by mdehghani65** [comment]
havn't tried but it may be a good idea. thx for mentioning
