### ISSUE TITLE
don't do email confirmation once successfully registered

### ISSUE THREAD

**Issue by mejuliver** [delight-im/PHP-Auth#132]
is there a way to bypass the email confirmation after a user has been successfully created his/her registration? like after he/she register, he/she can use his/her credentials right away to login. If so possible, please illuminate me.

**Comment by ocram** [comment]
Thanks, this is unfortunately not possible yet, but it’s already tracked in https://github.com/delight-im/PHP-Auth/pull/128.

For now, you could of course disable the email confirmation entirely by omitting the callback, as suggested in the README.
