### ISSUE TITLE
Google 2FA

### ISSUE THREAD

**Issue by macrel** [delight-im/PHP-Auth#133]
When using this library, would it be possible to add Google 2FA as well? What's the recommended way to do this?

**Comment by ocram** [comment]
There is *experimental* support for two-factor authentication.

The two methods `Auth#login` and `Auth#loginWithUsername` have an optional fourth parameter named `$onBeforeSuccess` that takes a `callable` (e.g. an anonymous function) that receives the user’s ID as its single parameter and is executed before successful authentication. It must return `true` to proceed or `false` to cancel authentication:

```php
function ($userId) {
    // ...
    return false;
    // or
    // return true;
}
```

In that callback, you can check your second factor. That means you perform a normal login, but in that callback, you check (in your custom database table) if a second factor is required. If required, return `false` to make the attempt fail. If not required, return `true` to let authentication complete as usual.

In any case, catch `AttemptCancelledException` for your login attempt. If that exception is thrown, you may display an input field asking the user for their 2FA code and repeat the login request with that code, afterwards.

Let us know if that works for you, if there’s anything missing, or if the design is flawed.

In general, see https://github.com/delight-im/PHP-Auth/issues/34 as well.

**Comment by ocram** [comment]
It’s super late, but 2FA is finally here: https://github.com/delight-im/PHP-Auth/issues/318
