### ISSUE TITLE
Silly question about a User entity class implementation...

### ISSUE THREAD

**Issue by alturic** [delight-im/PHP-Auth#134]
I'm trying to understand how to make my own User entity, as you wouldn't really want to stuff the Auth class (if downloading without composer) with all sorts of methods, while at the same time being able to have a User class.

What I did currently was run a $auth = new Auth()... then directly after run an $auth->isLoggedIn() conditional, if true return a new UserEntity, passing in the $auth->getUserId(). 

That doesn't feel right though?

**Comment by ocram** [comment]
As with most questions, this doesn’t seem to be silly. But please explain in a little more detail what you’re trying to do exactly.

Adding your own class wrapping the user’s properties seems fine. But where do you want to integrate it? Which method returns the object of that class?

It’s correct that you can only create an instance (because only then there is an authenticated user) if `Auth#isLoggedIn` returns `true`. And it’s also correct that you’ll probably need the output of `Auth#getUserId`, among other things.

**Comment by alturic** [comment]
Well, silly from the standpoint of being somewhat fresh to OOP. So, I know the Auth class returns... Auth relating info, but as I assume most people, I'm looking to have a User class for things like ->firstName, ->lastName, etc, etc, etc. I know even this should be extracted out to say a Subscription class, but even if I made a god User class, $user->hasSubscription.

Now, your second part, makes it sound like having a User class, that get instantiated in a IF condition would be the only real way to handle it regardless?

**Comment by ocram** [comment]
Well, first name and last name is something that this library and its database schema don’t support, anyway. So it’s already up to you how to store and retrieve that data. Looks like something that would fit well into a custom database table and custom class in your application code.

How and where to instantiate that custom class is, again, up to you. But you obviously cannot instantiate a valid user object when `Auth#isLoggedIn` returns `false`, thus it would make sense to check that value.

If the user is indeed logged in, you may get the few other properties from this library (e.g. email address) and put them into the instance of your custom class as well.

Sorry, while I see what problems you are describing, I don’t really understand which specific questions you’d like to have answered. Apart from that, I’m not sure if this is really specific to this library (or instead is about your own application code only).
