### ISSUE TITLE
create admin

### ISSUE THREAD

**Issue by asadghazanfary** [delight-im/PHP-Auth#145]
hello every one

how can i set Role to custom user?

OR

how can i create user with ADMIN role?

thank you

**Comment by ocram** [comment]
Please see [the documentation](https://github.com/delight-im/PHP-Auth#assigning-roles-to-users) and [this other issue](https://github.com/delight-im/PHP-Auth/issues/136).

**Comment by asadghazanfary** [comment]
i have another question

i set SUPER ADMIN role to the custom user. and my question is:

How can I check if this user is a SUPER ADMIN and then log in after that?

**Comment by ocram** [comment]
Again, [here](https://github.com/delight-im/PHP-Auth#checking-roles) and [here](https://github.com/delight-im/PHP-Auth#checking-roles-1).

**Comment by asadghazanfary** [comment]
i want first check this user with current email and password is super admin and then login to system as super admin. but i think in this method you must first login to be able to get user id:
`$auth->admin()->doesUserHaveRole($userId, \Delight\Auth\Role::ADMIN)`

Did I guess right?
Please explain more what should I do?

**Comment by ocram** [comment]
If you want to check if the currently signed-in user is a super admin, use [this](https://github.com/delight-im/PHP-Auth#checking-roles).

If you want to check if *any* user is a super admin, specifying the user by their ID, use [this](https://github.com/delight-im/PHP-Auth#checking-roles-1).

If you want to sign in as a super admin, simply sign in as a user with that role.

**Comment by asadghazanfary** [comment]
@ocram 
Do you think this code snippet could be a solution to the explanations given above?

`
$auth->login($_POST['email'], $_POST['password'], $rememberDuration);
            try {
                if ($auth->admin()->doesUserHaveRole($auth->getUserId(), \Delight\Auth\Role::ADMIN)) {
                    echo 'The specified user is an administrator';
                }
                else {
                    foreach($_SESSION as $sess_key => $sess_value) {
                        if (Helper::startsWith($sess_key, 'auth_')) {
                            \Delight\Cookie\Session::delete($sess_key);
                        }
                    }
                }
            }
            catch (\Delight\Auth\UnknownIdException $e) {
                die('Unknown user ID');
            }
`
