### ISSUE TITLE
please add method 

### ISSUE THREAD

**Issue by vahidalvandi** [delight-im/PHP-Auth#146]
if user no have role logout

` $this->auth->nohasAnyRoleLogout( \Delight\Auth\Role::MODERATOR,\Delight\Auth\Role::ADMIN,\Delight\Auth\Role::SUPER_ADMIN );
`

**Comment by ocram** [comment]
That seems a little bit too specific.

But the fundamental methods that you need are already there.

```php
if (!$auth->hasAnyRole(...\Delight\Auth\Role::getValues())) {
    $auth->logOut();
}
```

Does that work?
