### ISSUE TITLE
permission not work

### ISSUE THREAD

**Issue by vahidalvandi** [delight-im/PHP-Auth#147]
i set MAINTAINER role but after check roles it must return to logout page

```
try {
	$this->auth->admin()->addRoleForUserById(1, \Delight\Auth\Role::MAINTAINER);
}
catch (\Delight\Auth\UnknownIdException $e) {
	die('Unknown user ID');
}

if(!($this->auth->hasAnyRole(
	\Delight\Auth\Role::SUPER_ADMIN,
	\Delight\Auth\Role::COORDINATOR,
	\Delight\Auth\Role::ADMIN,
	\Delight\Auth\Role::EMPLOYEE
))) Url::redirect('logout');
```

**Comment by ocram** [comment]
Thanks!

Please see the [updated documentation](https://github.com/delight-im/PHP-Auth/commit/df990b5b75ffd3bb6c44cb43e0cfcd572ba37166).

It may take a few minutes for this change to show up, so checking directly afterwards will usually not succeed.

From our experience, the use case where you modify roles for the *current user themself* (other than directly after registration) is rare. In most cases, you are signed in as an administrator and add roles to *another user’s* account.
