### ISSUE TITLE
Confirmation mail for already verified users

### ISSUE THREAD

**Issue by megapcgames** [delight-im/PHP-Auth#148]
Why does it allow me to send back the confirmation message, when the account is already verified?

In the database the user has "1" in "verified".

Should I do the check on my own?

**Comment by ocram** [comment]
Thanks!

So you are using either `Auth#resendConfirmationForEmail` or `Auth#resendConfirmationForUserId`?

Right now, the behavior is that it checks the `users_confirmations` table and re-sends the latest attempt that has been stored there, i.e. which has not been successful yet.

If the user has already verified their email address, why would they try to verify it again?

And if the user verified their email address twice, would that be a problem?

Moreover, the email confirmation is not only used when confirming one’s email address initially, but also when changing one’s email address to a new address.

**Comment by megapcgames** [comment]
Thank you very much for answering.

Thinking well I do not care that they can send the confirmation message again.
