### ISSUE TITLE
how i can set role for method in constractor

### ISSUE THREAD

**Issue by vahidalvandi** [delight-im/PHP-Auth#150]
i have class sample class i need check user have permission to access create or edit method ?
this code check role for all methods . i need check user have permission for access create method?

```
class sample {

function __construct()
{
	 			if(!$this->auth->hasAnyRole(

				\Delight\Auth\Role::SUPER_ADMIN,
				\Delight\Auth\Role::COORDINATOR,
				\Delight\Auth\Role::ADMIN,
				\Delight\Auth\Role::EMPLOYEE

		         	)) Url::redirect('logout');
}
public function create(){

}

public function edit(){

}

}
```

**Comment by ocram** [comment]
What’s your specific question?

The code looks fine. Do you want to implement a similar check in the `create` method? What’s the problem with that?

**Comment by vahidalvandi** [comment]
i have application and have 3 main role , admin , super_admin , user
i went control logic code with user role , for example after login show each panel related by role .
...........
