### ISSUE TITLE
The fastest way to check the session

### ISSUE THREAD

**Issue by megapcgames** [delight-im/PHP-Auth#151]
I need to redirect users already logged in to a page, but with `$auth->isLoggedIn()` I need to call the library and declare `$auth`.

Is there any way to do a quick check without having to call the library, connect to the database, etc?

**Comment by ocram** [comment]
Are you sure that this `Auth` instance would be too much overhead and that this specific check on individual endpoints would be the bottleneck of your application?

Anyway, if you really want, you can simply duplicate the method in your own code:

https://github.com/delight-im/PHP-Auth/blob/4b3f2ab91c52958d1ae21651679372c3d3b2a0b3/src/Auth.php#L1409

As you can see, the implementation is extremely simple and doesn’t depend on any other components, except for the constants which you can inline.

Finally, the library may do more than this, e.g. receive instructions for remote logouts. If you need an *authoritative* answer, you always have to check the library. And that specific implementation may be subject to change, of course, so you must keep it up-to-date and check if the library’s implementation changes.
