### ISSUE TITLE
PHPSESSID is not send cross origin

### ISSUE THREAD

**Issue by dunky11** [delight-im/PHP-Auth#154]
I'm using a react app running on localhost:3000 which makes ajax requests to our website. We recently switched our authentification system from using WordPress authentification to this repository.

Since then, using the same settings inside ajax and on our web server, our authentification cookies are not sent cross origin. However, it's working when requesting them from the same domain.

Our request:

```
fetchLoginStatus = () => {
    const ajax = new XMLHttpRequest();
    ajax.withCredentials = true;
    ajax.open("POST", "https://our-website.com/src/php/checkLoggedIn.php");
    ajax.onload = () => {
      const response = JSON.parse(ajax.responseText);
    };
    ajax.send();   
};
```

Our request headers (from localhost:3000):

```
:authority: my-website.com
:method: POST
:path: /src/php/checkLoggedIn.php
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
content-length: 0
cookie: plesk-items-per-page; plesk-sort-field, phpMyAdmin; databases-active-list-state-collapsed; plesk-list-type; io=R_dL3fjUEYe64ykHAAAp; isAsyncProgressBarCollapsed=true; PLESKSESSID; plesk-sort-dir;
origin: https://localhost:3000
referer: https://localhost:3000/
```

Our response headers (we are running an nginx server):

```
access-control-allow-credentials: true
access-control-allow-headers: origin, x-requested-with, content-type 
access-control-allow-methods: PUT, GET, POST, DELETE, OPTIONS access-` 
control-allow-origin: https://localhost:3000 
cache-control: no-store, no-cache, must-revalidate 
content-encoding: br  
content-type: text/html; charset=UTF-8 
date: Sun, 10 Mar 2019 15:26:08 GMT 
expires: Thu, 19 Nov 1981 08:52:00 GMT pragma: 
no-cache server: nginx 
set-cookie: PHPSESSID=someId; 
path=/; SameSite=Lax status: 200 
vary: Accept-Encoding 
x-powered-by: PleskLin`
```

When I don't send the request cross-origin PHPSESSID is inside the cookies of my request headers. However when I send the request from localhost:3000 it's not there.

Does somebody know how I can send the PHPSESSID from localhost too?

Thanks for any help in advance!

**Comment by ocram** [comment]
Thanks!

So your React app is on `localhost:3000` and your backend (using this library) is on `our-website.com`, right? For authentication, the backend is used and stores cookies on your device. So it will be `our-website.com` which has the session cookie. For AJAX requests from `localhost:3000` to your backend, you expect your cookies to be sent back to your backend, but they aren’t. Is that all correct?

If so, could you try making the following temporary changes?

 * `vendor/delight-im/auth/src/UserManager.php`
   * Replace `Session::regenerate(true);` with `Session::regenerate(true, null);`
 * `vendor/delight-im/auth/src/Auth.php`
   * Replace `@Session::start();` with `@Session::start(null);`
   * Replace `Session::regenerate(true);` with `Session::regenerate(true, null);`
   * After `$cookie->setSecureOnly($params['secure']);` append `$cookie->setSameSiteRestriction(null);` in all three (!) occurrences

**Comment by dunky11** [comment]
Thank you really much, works now.

Great library by the way.

**Comment by ocram** [comment]
Thanks, glad to hear that it works!

We’ll soon add an option for this so that it can be toggled more easily: https://github.com/delight-im/PHP-Auth/issues/120
