### ISSUE TITLE
Incorrect table name in Auth.php

### ISSUE THREAD

**Issue by bleutzinn** [delight-im/PHP-Auth#156]
I'm using your excellent PHP-Foundation library, however the problem I encounter is in this one.

In each controller I refer to my Sqlite database as:
```
$db = new \PDO('sqlite:' . $app->getStoragePath('/db/app.sqlite'));
	$auth = new \Delight\Auth\Auth($db);
```

Then as a test and hardcoding the credentials, I created a new user like this:
```
$userId = $auth->register('me@example.com', 'my_secret', 'JohnD');
```

This successfully creates a new user entry in the database.

To login the user I use this code:
```
class LoginController {

	public static function tryLogin(App $app) {
		
	$db = new \PDO('sqlite:' . $app->getStoragePath('/db/app.sqlite'));
	$auth = new \Delight\Auth\Auth($db);

	try {

		$userEmail = $app->input()->post('email', TYPE_EMAIL);
		$password = $app->input()->post('password');
		$auth->login($userEmail, $password);

		echo 'User is logged in';
	}
```

Now when I try to login that user by doing a POST request to `/login` (the ` LoginController` route) I get an error stating "no such table **usersusers**":
```
Delight\Auth\DatabaseError: SQLSTATE[HY000]: General error: 1 no such table: usersusers in file /fs_path/vendor/delight-im/auth/src/Auth.php on line 165
Stack trace:
  1. Delight\Auth\DatabaseError->() /fs_path/vendor/delight-im/auth/src/Auth.php:165
  2. Delight\Auth\Auth->resyncSessionIfNecessary() /fs_path/vendor/delight-im/auth/src/Auth.php:56
  3. Delight\Auth\Auth->__construct()  /fs_path/vendor/delight-im/foundation-core/src/App.php:93
  4. Delight\Foundation\App->__construct()  /fs_path/index.php:77
```

What am I doing wrong here?

**Comment by ocram** [comment]
Thanks for your question and the perfect description!

Did you set `DB_PREFIX` in `config/.env` of [PHP-Foundation](https://github.com/delight-im/PHP-Foundation) to a non-empty value perhaps?

**Comment by bleutzinn** [comment]
You are right. I did set "users" as the `DB_PREFIX` and since registration worked didn't think that could be causing the problem,

I now have no prefix set and all is well.

Thanks a lot for your help.

**Comment by ocram** [comment]
No problem. Happy to hear that it works now.
