### ISSUE TITLE
Session refuses to clear in Firefox after restart

### ISSUE THREAD

**Issue by meshachviktor** [delight-im/PHP-Auth#157]
I did a little testing on the index.php file that came with PHP-Auth. I created an account and logged in with the account afterwards with the "Remember" dropdown set to "No" on Google Chrome and it worked as expected -- after a restart of my browser, the session was gone but firefox still remembers the session somehow. What do you think is wrong, please? I made no modification to the index.php file besides changing the database it will connect to which it does without any problem. I made no modification whatsoever to the MySQL Database file.
Environment:
Browser: Firefox 64.0.2 (did not work with Remember set to "No")
Browser: Chrome 73.0.3683.86 (worked with Remember set to "No")
MySQL Server: 5.7.24
Server: Apache 2.4.35 running under laragon

**Comment by ocram** [comment]
Thanks for your feedback!

In Firefox, you can go to the settings and adjust whether Firefox should clear cookies if you close the browser, or whether Firefox should restore the old browser session if you open the browser the next time.

When working with the `tests/index.php` file, you could open the developer tools in Firefox and go to the “Network” tab. Then, both on first visit and after signing in, open the relevant request and share the `Set-Cookie` HTTP response header here.

Alternatively, go to the “Storage” tab, choose “Cookies”, and share the overview of which cookies exist and when they expire.

That would help us debug this issue.

**Comment by meshachviktor** [comment]
Solution number one worked for me. Thank you.
