### ISSUE TITLE
Using built in SQL Functions

### ISSUE THREAD

**Issue by Mobles** [delight-im/PHP-Auth#158]
I saw in the code you have created your own functions for selecting, inserting etc just using sql queries for things, is it possible ot use those functions without having to rewrite them?

I've tried using the namespace for it as you did in Auth.php etc but It doesn't seem I can access those functions.

Im not great at PHP and the whole class based structure so I was just seeing if it is possible, I've gotten it to a point I can access it but it's static so I'd have to instantiate it, but I'm already connected through your PDO class PdoDsn I think it is.

**Comment by ocram** [comment]
Are you perhaps referring to [our database component](https://github.com/delight-im/PHP-DB), which is also open-source and available separately with detailed documentation?

**Comment by Mobles** [comment]
Thank you so much, sorry if I confused you pahah, but yes :)

**Comment by ocram** [comment]
No problem!
