### ISSUE TITLE
setting email verification expiration time

### ISSUE THREAD

**Issue by acodispo** [delight-im/PHP-Auth#161]
Any way to set the expiration time for email verification tokens? I think it is probably 24 hours by default. Thanks in advance!

**Comment by ocram** [comment]
Not yet, sorry. It’s indeed 24 hours right now, which is hard-coded [here](https://github.com/delight-im/PHP-Auth/blob/4b3f2ab91c52958d1ae21651679372c3d3b2a0b3/src/UserManager.php#L348).

Doesn’t that limit work for you? Users can re-request their confirmation as well.

**Comment by acodispo** [comment]
Our users apparently have a lot of trouble clicking on the link within 24 hours. :-)

I implemented the re-sending feature but as an admin feature, I forgot that it can be used as a way for a user to request a re-send. I'll implement that, and the problem should be solved.

Thanks for the quick answer!
