### ISSUE TITLE
Cannot modify header information

### ISSUE THREAD

**Issue by Duolabs** [delight-im/PHP-Auth#162]
Hi all,

Thanks for this great auth you are providing. I like it a lot but now I am facing some issue and I cannot solve them after 2 days of sleepless work.

PHP Version 7.0.33

_Warning: Cannot modify header information - headers already sent by (output started at /home1/..../index.php:1) in /home1/....../vendor/delight-im/auth/src/Auth.php on line 78

Warning: Cannot modify header information - headers already sent by (output started at /home1/..../index.php:1) in /home1/....../vendor/delight-im/auth/src/Auth.php on line 83

Warning: Cannot modify header information - headers already sent by (output started at /home1/..../index.php:1) in /home1/....../vendor/delight-im/auth/src/Auth.php on line 85

Warning: Cannot modify header information - headers already sent by (output started at /home1/..../index.php:1) in /home1/....../vendor/delight-im/auth/src/Auth.php on line 88

Warning: Cannot modify header information - headers already sent by (output started at /home1/..../index.php:1) in /home1/....../vendor/delight-im/auth/src/Auth.php on line 89

Warning: Cannot modify header information - headers already sent by (output started at /home1/..../index.php:1) in /home1/....../vendor/delight-im/auth/src/Auth.php on line 90

Location: https://..mywebsite../dashboard.php
Warning: Cannot modify header information - headers already sent by (output started at /home1/.../index.php:1) in /home1/.../index.php on line 31

I have to admit thay my dumb host provider changed something and it is no longer working.

What I tried is:
1. Check the <?php ?> for blank spaces -> no result
2. remove line 78 on Auth.php -> noresult
3. Pray for your help :)

I think the provider won't let me modify the http.conf as mentioned here: https://github.com/delight-im/PHP-Auth/issues/77

Please help ....

**Comment by Duolabs** [comment]
_Update..._

After finding a damned <!DOCTYPE html> at the beginning of my login page I landed to:

Warning: Cannot modify header information - headers already sent by (output started at /home1/..../index.php:1) in /home1/....../vendor/delight-im/auth/src/Auth.php on line 78

Warning: Cannot modify header information - headers already sent by (output started at /home1/..../index.php:1) in /home1/....../vendor/delight-im/auth/src/Auth.php on line 83

Warning: Cannot modify header information - headers already sent by (output started at /home1/..../index.php:1) in /home1/....../vendor/delight-im/auth/src/Auth.php on line 85

Warning: Cannot modify header information - headers already sent by (output started at /home1/..../index.php:1) in /home1/....../vendor/delight-im/auth/src/Auth.php on line 88

Warning: Cannot modify header information - headers already sent by (output started at /home1/..../index.php:1) in /home1/....../vendor/delight-im/auth/src/Auth.php on line 89

Warning: Cannot modify header information - headers already sent by (output started at /home1/..../index.php:1) in /home1/....../vendor/delight-im/auth/src/Auth.php on line 90


Location: https://..mywebsite../dashboard.php
Warning: Cannot modify header information - headers already sent by (output started at /home1/.../index.php:1) in /home1/.../index.php on line 31

**Comment by Duolabs** [comment]
Partial fix is removing the   `echo ("$headerusl");` from my index.php but now when I log out:

Fatal error: Uncaught Delight\Auth\HeadersAlreadySentError in /home1/..../vendor/delight-im/auth/src/Auth.php:550 Stack trace: #0 /home1/...../vendor/delight-im/auth/src/Auth.php(518): Delight\Auth\Auth->setRememberCookie(NULL, NULL, 1555279981) #1 /home1/..../vendor/delight-im/auth/src/UserManager.php(404): Delight\Auth\Auth->deleteRememberDirectiveForUserById(69) #2 /home1/.../vendor/delight-im/auth/src/Auth.php(430): Delight\Auth\UserManager->forceLogoutForUserById(69) #3 /home1/.../User_Logout.php(22): Delight\Auth\Auth->logOutEverywhereElse() #4 {main} thrown in /home1/.../vendor/delight-im/auth/src/Auth.php on line 550

**Comment by ocram** [comment]
I don’t think that other issue (which you referenced in your first message) is related.

Why would you want to change anything in your server configuration?

Removing random lines from your own application code or from this library doesn’t seem like a proper solution, either.

Instead, you need to fix the actual problem, which should be pretty easy to find:

Somewhere before you create an instance of `Auth` or before you call methods on that instance, you are already sending output to the client, i.e. text or data.

The issues https://github.com/delight-im/PHP-Auth/issues/26 and https://github.com/delight-im/PHP-Auth/issues/44 and https://github.com/delight-im/PHP-Auth/issues/143 are related, but it’s not always leading or trailing whitespace, it can be visible text as well.
