### ISSUE TITLE
Call to undefined function Auth

### ISSUE THREAD

**Issue by AndreaDrago96** [delight-im/PHP-Auth#163]
Hi everyone,

I followed the install procedures, and required the composer autoloader file, but the classes are still not loaded.

What I did:

1. Installed composer globally
2. Required this package (in the vendor directory I can see it with all its dependencies)
3. Required the autoloader inside the php file
4. Used the Auth function

Here it is my code:

```
require __DIR__.'/../vendor/autoload.php';
require __DIR__.'/../secured/settings.php';

try {
    $conn = new PDO("mysql:host=$db_host;dbname=$db", $public_user, $public_password);
    $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
}
catch (PDOException $e) {
    echo "Connection failed: " . $e->getMessage();
}

$auth = \Delight\Auth\Auth($conn);
```

At the last line it throws this error:

`[Tue Apr 16 12:17:01.287393 2019] [:error] [pid 29181] [client 127.0.0.1:49476] PHP Fatal error:  Call to undefined function Delight\\Auth\\Auth() in /var/www/site/dist/backend/signup.php on line 14`

Executing "composer show -i" inside the folder shows that the packages are installed:

```
delight-im/auth   v8.1.0 Authentication for PHP. Simple, lightweight and secure.
delight-im/base64 v1.0.0 Simple and convenient Base64 encoding and decoding for PHP
delight-im/cookie v3.1.2 Modern cookie management for PHP
delight-im/db     v1.3.0 Safe and convenient SQL database access in a driver-agnostic way
delight-im/http   v2.0.0 Hypertext Transfer Protocol (HTTP) utilities for PHP
```
Is there something I'm missing?

**Comment by ocram** [comment]
First, thanks for your detailed description.

But yes, there’s indeed something you’ve missed:

`\Delight\Auth\Auth` is not a function but a constructor, so you have to prepend the `new` keyword.

As in (and as documented):

```php
$auth = new \Delight\Auth\Auth($conn);
```

**Comment by AndreaDrago96** [comment]
Thank you very much
... and sorry for missing such a smiple typo -.-
