### ISSUE TITLE
Register without username

### ISSUE THREAD

**Issue by megapcgames** [delight-im/PHP-Auth#165]
I would like to omit the username in the registry, but I do not know what I should do with the third parameter of Auth#register.

Thanks and sorry for my bad english.

**Comment by megapcgames** [comment]
I've already found it. I will simply remove it or change it to NULL when I want to include email verification.

`@param string|null $username (optional) the username that will be displayed`

**Comment by ocram** [comment]
Yes, that’s the correct solution!
