### ISSUE TITLE
change email without verification

### ISSUE THREAD

**Issue by acodispo** [delight-im/PHP-Auth#166]
According to the readme email verification is optional during registration. You can leave out the third parameter to `Auth#register` and the user will immediately be active.

I think I am correct in understanding that `Auth#changeEmail` does not have this option. I see a "Too Few Arguments" error when I try leaving off the 2nd parameter.

If the above is the case, I'd like this issue to serve as a feature request, that `changeEmail` have the same option to skip verification as `register` does. If skipping verification is an option during registration of a new user, I would think it should be acceptable when changing an email address, as well.

Thanks for your time & consideration!

**Comment by ocram** [comment]
Thanks!

You are correct in everything that you write.

Could you explain why you think that letting users change their email addresses without verification may be a good idea? This will result in a data set where you don’t know which email address you can trust and rely on and which you can’t.

The only reason this has been enabled for the sign up is that developers may choose to use something entirely different as an identifier, e.g. an external (verified) identifier, a phone number, or a random string. For example, with a phone number, you could perform the verification *before*, and when you have verified the supplied number, you can create a “virtual” email address like “0123456789@localhost”.

Finally, if you are really sure this is a good idea, could you perhaps just verify the email address immediately without any user interaction, e.g. with something like the following as a confirmation callback?

```php
function ($selector, $token) use ($auth) {
    try {
        $auth->confirmEmail($selector, $token);
    }
    catch (\Delight\Auth\InvalidSelectorTokenPairException $e) {
        die('Invalid token');
    }
    catch (\Delight\Auth\TokenExpiredException $e) {
        die('Token expired');
    }
    catch (\Delight\Auth\UserAlreadyExistsException $e) {
        die('Email address already exists');
    }
    catch (\Delight\Auth\TooManyRequestsException $e) {
        die('Too many requests');
    }
}
```

**Comment by acodispo** [comment]
> Could you explain why you think that letting users change their email addresses without verification may be a good idea?

Specifically: I'm working with a code-base that has an existing legacy email confirmation system for some emails that don't have full user accounts associated with them. This is currently running in tandem with php-auth (for verification of emails tied to full user accounts).

I'm anticipating a need to allow a change of email from a php-auth verified email to a legacy-verified email, if that makes any sense.

Your suggested solution should work fine, though! If I get into a situation where the user wants to change the account email address to an email I know they've verified through the legacy system, I'll just use what you've suggested.

Thanks as always for your quick response!

**Comment by ocram** [comment]
Thanks!

Your use case makes sense, of course.

Please report back if the suggested solution does not work.
