### ISSUE TITLE
Get Roles from user by id return error.

### ISSUE THREAD

**Issue by daebak74** [delight-im/PHP-Auth#167]
I don't know if I misunderstanding the method I need to get all the roles from an user by his id so I try:

I am using the PHP Foundation

$app->$auth->admin()->getRolesForUserById($userId); 

this user hasn't role but is normal to receive this error ?

Cannot access empty property ?

Thanks.

**Comment by daebak74** [comment]
My mistake. I copied from auth rep and I forgot to change is auth() and not $auth :(

**Comment by ocram** [comment]
No problem! Thanks for sharing the solution.
