### ISSUE TITLE
CreateUser verified field value is 1

### ISSUE THREAD

**Issue by daebak74** [delight-im/PHP-Auth#169]
Just a question, is normal if I create a new user with this metod the verified field default value is 1 ?

$app->auth()->admin()->createUserWithUniqueUsername($email, $password, $username);

If by default is set in 1 means that the email is verified is correct ?

Thanks.

**Comment by ocram** [comment]
Yes, that’s correct. This is *you* creating users directly *as an administrator*, so there’s no untrusted input in the sense that no user data is received from unknown people with unclear motivations. In most cases, developers even *want* the new accounts to be active right away.
