### ISSUE TITLE
Configurable database table prefix

### ISSUE THREAD

**Issue by ocram** [delight-im/PHP-Auth#17]
We should introduce an optional database table prefix and make it configurable.

The default prefix will be the empty string, of course.

That option could be passed to the constructor of the `Auth` class as another parameter called `$databaseTablePrefix`.

**Comment by waqas-yousaf** [comment]
Can you please include an example? Great work btw.

**Comment by ocram** [comment]
@waqas-yousaf Thanks! What do you want to see an example for, specifically? Do you want to see an example of how the custom database prefix is set up and used with your database? Please note that this feature is not available yet, but just planned for the future.

**Comment by waqas-yousaf** [comment]
@ocram ohh! my bad. I should have read documentation properly. I think my project would do fine without a table prefix too. I am gonna go ahead with it anyway. again. great work.

**Comment by odahcam** [comment]
A table prefix option would be nice, some DB models are created using prefix in column names to avoid any ambiguous situations and sometimes remove those prefixes is not an option.

**Comment by ocram** [comment]
Implemented in:

 * https://github.com/delight-im/PHP-Auth/commit/5274dd5f8e03340b7f437408d889f0bd923fa9a5
 * https://github.com/delight-im/PHP-Auth/commit/83f2ab0a9c1211862bb93f332726fa5e65f7ca82

This is available in a new major version, `v6.0.0`, which comes with a few breaking changes. For a guide on how to upgrade, please see the migration notes in `Migration.md`.

**Comment by fdiengdoh** [comment]
been away, for a while, this is a very good feature. Thanks for implementing this one.
