### ISSUE TITLE
Additional sign up variables

### ISSUE THREAD

**Issue by binoculars88** [delight-im/PHP-Auth#171]
Is there an easy way to register users with additional variables?
I'm thinking of address information or opt-in for newsletters etc.
Or would you recommend to keep them in a separate database table with the user ID to match them?

**Comment by acodispo** [comment]
I'm not the dev, but I've done what you're asking about in my own code using php-auth so I thought I'd chime in!

There's some good documentation here on doing this, which was all I needed to add my custom user info:

https://github.com/delight-im/PHP-Auth/#additional-user-information

And yes, the recommendation given by the developer is to use your own, separate tables.

**Comment by binoculars88** [comment]
> I'm not the dev, but I've done what you're asking about in my own code using php-auth so I thought I'd chime in!
> 
> There's some good documentation here on doing this, which was all I needed to add my custom user info:
> 
> https://github.com/delight-im/PHP-Auth/#additional-user-information
> 
> And yes, the recommendation given by the developer is to use your own, separate tables.

Thanks! Must have missed that section in the docs, I was looking for it in the registration section, not the accessing user information section.

So filling up a separate table after registration it is then, thanks!

**Comment by ocram** [comment]
@acodispo Thank you very much for your help!

@binoculars88 Good point! The relevant section is now referenced from the “Registration” section in the docs, as per https://github.com/delight-im/PHP-Auth/commit/54f6c5320a7103559937b09ff436a410c756171a.
