### ISSUE TITLE
SQL injections?

### ISSUE THREAD

**Issue by tmblog** [delight-im/PHP-Auth#173]
Hello great library thank you!
Just wondered does this library take care of validation and sanitization against injections?
Sorry if I have missed it in the documentation.

Thanks again.

**Comment by turbopixel** [comment]
The magic word is: [prepared statements](https://www.php.net/manual/de/mysqli.quickstart.prepared-statements.php).   
You can find the whole pdo code here: https://github.com/delight-im/PHP-DB/blob/master/src/PdoDatabase.php#L246

**Comment by ocram** [comment]
@turbopixel Thanks for your help!

@tmblog Yes, this library *should* provide protection against SQL injections. If it does not, it may be a bug, and we’ll be happy if you report it.
