### ISSUE TITLE
Login without password.

### ISSUE THREAD

**Issue by BinoyDarvin** [delight-im/PHP-Auth#174]
How to log in a user without password? By only giving email? I just added a 'login with google' button. I'll get email address from Google API. I need to use PHPAuth with this email to log in the user.

**Comment by ocram** [comment]
Not sure if this library here is really a good choice for that use case. Sorry!

Right now, you are always required to provide a password. It would be up to you to find a workaround, e.g. perhaps setting a hardcoded password (per user), or using some token from the identity provider (Google) as the password.

Most of what this library offers will be useless in your case, and what you actually need isn’t really here.

See also [this other issue](https://github.com/delight-im/PHP-Auth/issues/129).

**Comment by BinoyDarvin** [comment]
Okay. Thanks!
