### ISSUE TITLE
IdAm logout Issue

### ISSUE THREAD

**Issue by divyapai56** [delight-im/PHP-Auth#177]
I have an application with using IdAm for login, so it automatically logs in when we connect from the local. When we try to logout, on copy pasting the link back, it automatically logs in as all the session storages are restored using IdAm, how do we ensure once logged out, sessions cleared are not set back for that window?

Using angularJs with typescript and backend asp.net c#

**Comment by ocram** [comment]
Doesn’t seem you’re actually using this library in any way.

Feel free to reopen if you can describe your usage in more detail.
