### ISSUE TITLE
Get additional info on revisit

### ISSUE THREAD

**Issue by tmblog** [delight-im/PHP-Auth#180]
Hello once again I am finding this very useful and it definitely is one of the most feature rich libraries in terms of authorisation.

I am adding additional info as per your docs to session variables, what's the recommended way to load those data when the user revisits say after a few weeks having been remembered?

Currently I am checking like this:

```
if ($auth->isLoggedIn()) {
    echo 'logged in';
    if(!isset($_SESSION['user_address_1']))
    {
    //get from database and set in to session variables
    }
	}
```
Can you recommend any other ways or if indeed there is anything built in?

Thanks again!

**Comment by ocram** [comment]
Thanks!

The user revisiting your site either after a few minutes or only after a few weeks is exactly what the suggested code example is for, see [here](https://github.com/delight-im/PHP-Auth#additional-user-information).

If the user’s last visit has been a few minutes ago, the data will probably still be cached in the session data. If the last visit has been a few weeks ago, the data is probably not available in the cache anymore and will be fetched from the database or file system again, storing it in the cache.

Does that help?
