### ISSUE TITLE
New user without form

### ISSUE THREAD

**Issue by tmblog** [delight-im/PHP-Auth#182]
Hi I have a peculiar question, I want to be able to create a user directly in the database table without creating sign up forms as the project I am working with doesn't allow registrations just one user who can CRUD few other things.
I can see the fields inside the user table, and using bcrypt (10 passes) I can create a password to associate with the user.
Is it correct that the password is `bcrypt` 10 passes?
How can I create the selector and token to make the user remembered?
And what does the field `force_logout` do?
Thanks for your time.

**Comment by ocram** [comment]
Is there anything wrong with `Administration#createUser`, which is available from `Auth#admin`?

If you still wanted to create the database records yourself, you could certainly look up and use the same algorithm and parameters for password hashing, but those could very well change in the future, requiring your implementation to be adjusted, and potentially breaking it in the meantime. Anyway, I don’t think it’s necessary for you to create the records yourself, see above.

As for the selector and token for persistent logins (“remember me”), that is part of the login, while you only wanted to implement the registration part yourself, right?

The field `force_logout` is used for remote logouts, and can safely be left at its default value.

Hope that helps!

**Comment by tmblog** [comment]
Yes it does, I just ran the register script to create the user. Thanks again!

**Comment by ocram** [comment]
No problem!
