### ISSUE TITLE
Protect some pages with password only

### ISSUE THREAD

**Issue by tmblog** [delight-im/PHP-Auth#183]
Hello again! really finding this library useful and your support is really exceptional and highly appreciated!

I tried to protect 1 or 2 pages using [Auth#reconfirmPassword](https://github.com/delight-im/PHP-Auth#reconfirming-the-users-password) e.g. some pages are out of bounds even if user is logged in, in that case the password is required.

And I can see that it needs to used with [Auth#isRemembered](https://github.com/delight-im/PHP-Auth#checking-whether-the-user-was-remembered)

I think that only works if the user closes the browser and comes back to be logged in via the cookie.

What would be a way to protect some pages with password even if they are logged in?
I am trying to stop unauthorised access to certain pages for users if the device is left unattended.
Thank you!

**Comment by ocram** [comment]
Thanks for your appreciation!

It’s perfectly fine to use `Auth#reconfirmPassword` alone, without anything else, for the purpose you describe.

What the documentation says is just that, whenever `Auth#isRemembered` returns `true`, it makes sense to reconfirm the password as well before performing any sensitive operations. But it’s perfectly fine to reconfirm the password in other situations, too.
