### ISSUE TITLE
Question: Why are the user roles numbered by n^2?

### ISSUE THREAD

**Issue by podoco** [delight-im/PHP-Auth#191]
the roles here go up by a square of 2. what was your design for that?

```
        const ADMIN = 1;
	const AUTHOR = 2;
	const COLLABORATOR = 4;
	const CONSULTANT = 8;
	const CONSUMER = 16;
	const CONTRIBUTOR = 32;
	const COORDINATOR = 64;
	const CREATOR = 128;
	const DEVELOPER = 256;
	const DIRECTOR = 512;
```

**Comment by ocram** [comment]
These are flags or [bit masks](https://en.wikipedia.org/wiki/Mask_(computing)) used with [bit fields](https://en.wikipedia.org/wiki/Bit_field). If `ADMIN` is `1` and `AUTHOR`is `2`, a user with both of these roles would have its bit field set to `3`.

If you are merely using the library, as opposed to working on its development, you don’t need to care about the implementation. You can just use the named constants and don’t think about the values or how they are used. The implementation may even change in the future.

**Comment by podoco** [comment]
> If you are merely using the library, as opposed to working on its development, you don’t need to care about the implementation.
I like to learn! 

Thank you for the explanation. Very interesting. I love the library. Keep up the great work!

**Comment by ocram** [comment]
> I like to learn!

That’s great!

Just wanted you (and others) to know that you really don’t have to pay attention to the values of those constants in *usages* of this library.

> I love the library. Keep up the great work!

Will try to do, thanks for your appreciation!
