### ISSUE TITLE
Get user email by selector

### ISSUE THREAD

**Issue by scifinder** [delight-im/PHP-Auth#193]
Hello!
How, after resetting the password in this way (`$auth->resetPassword($_POST['selector'], $_POST['token'], $_POST['password']);`), to find out the user's email address to send him a critical notification? `$auth->getEmail()` is empty.

**Comment by ocram** [comment]
Great question, thanks!

`Auth#getEmail` is empty because no user is signed in at that time.

We could change `Auth#resetPassword` to return either the user’s ID or their email address, or even both. What do you think?

**Comment by scifinder** [comment]
Thanks for your reply
You already have a user ID here:
https://github.com/delight-im/PHP-Auth/blob/1757ad3fd1eb06a014e78672749360b92be7d397/src/Auth.php#L1248
You can simply return it from the `Auth#resetPasswrod`. And then add a method like `admin()->getUserEmailById($userId)`. I think this will be the optimal solution.

**Comment by ocram** [comment]
Yes, we already have a result set from the database there, and it will be easy to return the data.

But we cannot see any use case for retrieving the user ID there. Can you?

So, right now, we think it would be best to simply return the email address only.

By the way, note that, when the password reset is initiated, the user already receives an email. So what you want to do here (sending a second email on completion of the reset) is certainly a good practice, but not critical.

**Comment by scifinder** [comment]
I still think it would be great to add a method like `Administration#getUserEmailById` - this method is still sometimes required. In this case, I see a use case for retrieving the user ID from `Auth#resetPassword`. But, in general, I think we will be glad to any decision. Perhaps the option you are offering is even more optimal.

Yes, I hastened, stating that this was a critical notice. But in my case it is quite important.

**Comment by ocram** [comment]
The method `Auth#resetPassword` now returns both the user’s ID and their email address.

Implemented in https://github.com/delight-im/PHP-Auth/commit/5214da1f598703e1103fe95be6ae7d7164989bd1 and documented in https://github.com/delight-im/PHP-Auth/commit/49c70eff414f045c3f640069c9f7e0671ab3c247
