### ISSUE TITLE
2FA authentication

### ISSUE THREAD

**Issue by ponasromas** [delight-im/PHP-Auth#197]
At current time and regulations it is important to have more than 1 method of authorization. Password + 2FA (example.: Google Auth) would be awesome to see in this library.

**Comment by ocram** [comment]
Sure, it’s definitely good to have. Though there is a variety of implementations, and we should probably support *all* of them, in a generic way.

Are [this issue](https://github.com/delight-im/PHP-Auth/issues/34) and [this issue](https://github.com/delight-im/PHP-Auth/issues/133) and [this commit](https://github.com/delight-im/PHP-Auth/commit/0909291cf164313d2d8c04a54a49aed7b5e03382?w=1) helpful perhaps?

**Comment by ponasromas** [comment]
At least Google 2FA would be awesome to have :) . Thank you for that commit, I will try to assemble something.

**Comment by ocram** [comment]
There are various libraries out there already that implement support for Google Authenticator:

 * https://github.com/antonioribeiro/google2fa
 * https://github.com/RobThree/TwoFactorAuth
 * https://github.com/PHPGangsta/GoogleAuthenticator
 * https://github.com/lelag/otphp
 * https://github.com/chregu/GoogleAuthenticator.php

Further, some people might want hardware devices or WebAuthn support.

So ideally, this library here is only adjusted so that you can combine it with any of those 2FA components.

Why not start with one of these libraries and report what’s missing here to make it work? It would be great if we could enable side-by-side usage of this library here and some of those libraries with a few minor changes.

**Comment by nssnl** [comment]
I'm working on implementing 2FA. I want to offer several ways, including SMS and time based OTP's (e.g. through Google Autenticator / Authy, etc). Along with entering the 2FA code, the user can opt to "Trust the device". In that case a cookie will be saved with a unique identifier that is also saved in the database.

To this end, the [commit](https://github.com/delight-im/PHP-Auth/commit/0909291cf164313d2d8c04a54a49aed7b5e03382?w=1) is useful, but I want to be more flexible in terms of error reporting - as only TRUE or FALSE is returned. Also if a user is logged in while in the OTP auhentication process, it is easier to retrieve the mobile phone number of a user in case of resending SMS - see below.

To this end, I was thinking of logging the user in, and then checking in an additional user table whether 2FA is verified through the "Trust the device"-cookie and/or current session. If not verified, a 2FA screen is shown with the different options: time based OTP and fallback SMS. User can opt for either one. If the user opts for SMS, for example, and the SMS is not received within 30sec, the user is able to request for resending the SMS. If the user would not be logged in (i.e. if the [commit](https://github.com/delight-im/PHP-Auth/commit/0909291cf164313d2d8c04a54a49aed7b5e03382?w=1) is used), this would only be possible with a new login request, as the mobile number is not known.

To verify the 2FA I was thinking of the following approach:
- If the user enters a valid 2FA code (either time based or through SMS), a 2FA verifier is saved into the **session**.
- In addition, the user can opt to trust the device. If so, a cookie is saved. When no 2FA verifier is present in the session, the cookie will be checked. If present, the session is updated automatically.

Both ways ensures that user is considered to be 2FA-verified. If a user enters an incorrect code X times, `$auth->logOutEverywhere();` is triggered. 

What do you think of the above, does it make sense?

**Comment by ocram** [comment]
It’s super late but it’s finally here: https://github.com/delight-im/PHP-Auth/issues/318
