### ISSUE TITLE
Does this library include validation, does it validate the username inputs and such?

### ISSUE THREAD

**Issue by GregsGrog** [delight-im/PHP-Auth#199]
Title pretty much describes the question, couldn't see anything about validation in the docs.

Thanks for the help!

**Comment by ocram** [comment]
Thanks!

Validation needs rules – whose rules?

Should we just impose some arbitrary rules on inputs that you might not even agree with?

The library applies input sanitization for security, though. But the goal is, while keeping things safe, not to impose *any* rules on inputs, where possible.

If you have your own business rules that need to be implemented, just wrap your own checks around the calls to this library.

Does that help?

**Comment by GregsGrog** [comment]
Thats perfect! So the the idea is the library does what is needed to keep it secure but does not impose rules on what is submitted. So a password can be any length but any attacks in the form of SQL injection is dealt with?

**Comment by ocram** [comment]
Exactly! Glad that this works for you.

Though, by the way, when it comes to *lengths*, there *are* indeed some limits, such as the column length limits in your database, and algorithmic limits such as bcrypt’s [50–72 characters](https://www.php.net/manual/en/function.password-hash.php) (or even just bytes).
