### ISSUE TITLE
change user email address

### ISSUE THREAD

**Issue by acodispo** [delight-im/PHP-Auth#20]
There's a way to change the current user's password.

Is there a way to change the current user's email address?

**Comment by ocram** [comment]
Not yet, unfortunately.

Thanks for pointing this out!

We should definitely add support for this very soon. It can be done similar to the way the password reset has been implemented. Apart from that, we generate and verify those tokens for the activation email after registration already, so that can be re-used as well.

**Comment by acodispo** [comment]
Sorry that I don't have the skills to contribute, but thanks for putting it on the list!

**Comment by ocram** [comment]
Implemented in:

 * https://github.com/delight-im/PHP-Auth/commit/ec8e9eab4e94ddee79652a8124c83ceae6985b9d
 * https://github.com/delight-im/PHP-Auth/commit/f962008fc44f33758101a5d0f6820dc2c85aee7b
 * https://github.com/delight-im/PHP-Auth/commit/d14d929bc353e66e6cb54e0f8152bef3af365fec
 * https://github.com/delight-im/PHP-Auth/commit/b2e6f68a22d854bc67959c4926c72f665c5d26eb
 * https://github.com/delight-im/PHP-Auth/commit/28979925d72c2659dc545aab6c8d7ed144c59d1c
 * https://github.com/delight-im/PHP-Auth/commit/90c621aeb05f741d79b166537efd8c84c506ca9f
 * https://github.com/delight-im/PHP-Auth/commit/15f73567b6b423d62d970573372c079592cfcc02
 * https://github.com/delight-im/PHP-Auth/commit/af5ce5a0b4a7b12ebdde3a1bb4d92608593ec1a8
 * https://github.com/delight-im/PHP-Auth/commit/f13302b0143dd6191764faf55e079aeee299c35f
 * https://github.com/delight-im/PHP-Auth/commit/7b4c4bf0e1b8b05f7a7f215cd17661a9f314ef80
 * https://github.com/delight-im/PHP-Auth/commit/ea67c66bd12006cd051ec3a3369df1fd67408e12
 * https://github.com/delight-im/PHP-Auth/commit/39f9b00b45b5d1f783574bade3745a450cbfb4a4
 * https://github.com/delight-im/PHP-Auth/commit/e925a73ef880f773e7aafbfa2c97bd19a0ca3067
 * https://github.com/delight-im/PHP-Auth/commit/3809b9d5d5e2154714a460de2d99c6f6f4394708
 * https://github.com/delight-im/PHP-Auth/commit/59cd626bd01c8c9f099697d736d404b787f02200

This is available in a new major version, `v6.0.0`, which comes with a few breaking changes. For a guide on how to upgrade, please see the migration notes in `Migration.md`.
