### ISSUE TITLE
How to list users ?

### ISSUE THREAD

**Issue by Pix13** [delight-im/PHP-Auth#201]
Hi,
I think i've read the api back and forth, and i could not find a function to list all existing users, do i need to execute a standard SQL query on my users database for that ?

**Comment by ocram** [comment]
Sorry for that!

Thanks for your feedback, and you are right about this.

This is now documented: https://github.com/delight-im/PHP-Auth/commit/d8847fb197a1cb02794d0e0fa6d23cef28a8b846
