### ISSUE TITLE
Semantik error couse InvalidSelectorTokenPairException

### ISSUE THREAD

**Issue by JHerwig** [delight-im/PHP-Auth#204]
Following the guide if first create reset data:
```php
try {
    $auth->forgotPassword($_POST['email'], function ($selector, $token) {
        echo 'Send ' . $selector . ' and ' . $token . ' to the user (e.g. via email)';
    });

    echo 'Request has been generated';
}
catch (\Delight\Auth\InvalidEmailException $e) {
    die('Invalid email address');
}
catch (\Delight\Auth\EmailNotVerifiedException $e) {
    die('Email not verified');
}
catch (\Delight\Auth\ResetDisabledException $e) {
    die('Password reset is disabled');
}
catch (\Delight\Auth\TooManyRequestsException $e) {
    die('Too many requests');
}
```
And then update the password:
```
try {
    $auth->resetPassword($_POST['selector'], $_POST['token'], $_POST['password']);

    echo 'Password has been reset';
}
catch (\Delight\Auth\InvalidSelectorTokenPairException $e) {
    die('Invalid token');
}
catch (\Delight\Auth\TokenExpiredException $e) {
    die('Token expired');
}
catch (\Delight\Auth\ResetDisabledException $e) {
    die('Password reset is disabled');
}
catch (\Delight\Auth\InvalidPasswordException $e) {
    die('Invalid password');
}
catch (\Delight\Auth\TooManyRequestsException $e) {
    die('Too many requests');
}
```

But I get always InvalidSelectorTokenPairException:
While debugging i've found that you use `\password_verify($token, $resetData['token'])`.
But [password_verify](https://www.php.net/manual/de/function.password-verify.php) check a hash, not the equality.

![image](https://user-images.githubusercontent.com/14972078/77783996-1763b780-705a-11ea-82a3-d5bb3f233dd1.png)

**Comment by JHerwig** [comment]
I've found my mistake. Because I can't send mails on localhost, I've created the reset link by hand using the database data.
Sorry for inconvenient

**Comment by ocram** [comment]
Thanks, no problem!

Just to explain this again (perhaps for others as well):

You don’t have to send the reset token via email. You can send it via SMS as well, or even print it and send it via physical mail, or via any other means you consider reliable and trusted. (But, of course, what you actually want to do is verify the *email address*, not any physical address.)

What you *cannot* do, however, is restore the token from the database. And that’s exactly the point of hashing it, which you referred to.

The only place you can get the token is in the anonymous function passed to the registration method.

**Comment by JHerwig** [comment]
Or using the  [Re-sending confirmation request](https://github.com/delight-im/PHP-Auth#re-sending-confirmation-requests) like i do now.  👍

**Comment by ocram** [comment]
Yes, sorry.

> The only place you can get the token is in the anonymous function passed to the registration method.

That was wrong, of course, especially for this particular case.

What I should have said instead is that the only place to get the token is in the anonymous functions passed to `Auth#register`, `Auth#forgotPassword`, `Auth#changeEmail`, `Auth#resendConfirmationForEmail` or `Auth#resendConfirmationForUserId`.

**Comment by keeker** [comment]
Sorry to re-open but I'm also getting this error. I'm also running locahost so manually creating the reset link. 

I have no idea what i'm missing, like @JHerwig :) Can you explain further please.
