### ISSUE TITLE
The database connection must be an instance of either `PdoDatabase`, `PdoDsn` or `PDO`

### ISSUE THREAD

**Issue by Seb1929** [delight-im/PHP-Auth#205]
Hi.

So I'm loading mye database connection class with the composer autoloader and I'm getting that my connection is not an PDO connection.. while it is.

**Trying to connect to det database from the file:**
```
require __DIR__ . '../../../vendor/autoload.php';

$Database = new Database\Database();

$auth = new \Delight\Auth\Auth($Database->getConnection());

```

**Database connection class:**
```
namespace Database;

class Database {
	public function getConnection() {
		$db = new \PDO('mysql:dbname=app;host=localhost;charset=utf8mb4', 'root', 'root');
	}
}
```
Is this an bug that i can't use an autoloader because it can't get the connection type?

This is the error 

`Fatal error: Uncaught InvalidArgumentException: The database connection must be an instance of either `PdoDatabase`, `PdoDsn` or `PDO` in REMOVED MY PATH\vendor\delight-im\auth\src\UserManager.php:90 Stack trace: #0 REMOVED MY PATH\vendor\delight-im\auth\src\Auth.php(45): Delight\Auth\UserManager->__construct(NULL, NULL, NULL) #1 REMOVED MY PATH\app\public\dashboard\index.php(7): Delight\Auth\Auth->__construct(NULL) #2 {main} thrown in REMOVED MY PATH\vendor\delight-im\auth\src\UserManager.php on line 90`

**Comment by ocram** [comment]
Can you pass

```php
new \PDO('mysql:dbname=app;host=localhost;charset=utf8mb4', 'root', 'root')
```

as an argument directly instead of

```php
$Database->getConnection()
```

and see if anything changes?

I guess the bug must be somewhere in your code, because `PDO` instances are definitely accepted:

https://github.com/delight-im/PHP-Auth/blob/d8847fb197a1cb02794d0e0fa6d23cef28a8b846/src/UserManager.php#L84-L86

**Comment by Seb1929** [comment]
Hi.

Yeah. It was totaly a bug with my code. Just change up the connection code a bit then it worked. Thank you anyway! Also is it possible to donate?

**Comment by ocram** [comment]
Glad to hear that, thank you!

Your feedback and appreciation is a sufficient donation :)

**Comment by Seb1929** [comment]
I think i searched for a few weeks for an package like yours. Its perfect for my needs and so adaptable. So thank you for making this :)
