### ISSUE TITLE
Resend Verification Email

### ISSUE THREAD

**Issue by ceswebmaster** [delight-im/PHP-Auth#206]
What is the best way to send a verification email again with a new token/selector if the user takes longer than 24 hours to verify?

**Comment by ocram** [comment]
Doesn’t this work for you?

https://github.com/delight-im/PHP-Auth#re-sending-confirmation-requests

So there’s `Auth#resendConfirmationForEmail` and `Auth#resendConfirmationForUserId`.

**Comment by ceswebmaster** [comment]
Wow can't believe I missed that! Thank you

**Comment by ocram** [comment]
No problem, thanks!
