### ISSUE TITLE
Auto login after password reset

### ISSUE THREAD

**Issue by tmblog** [delight-im/PHP-Auth#208]
Hi what would be the recommended way to login someone after they have reset their password? Ideally without having to enter username and password into another form so straight after they have successfully updated the password like `confirmEmailAndSignIn`

Since I don't have their email handy I can't call the login function and sign them in.

Cheers

**Comment by ocram** [comment]
So you want some `Auth#resetPasswordAndSignIn` in addition to `Auth#resetPassword`, analogous to `Auth#confirmEmailAndSignIn` for `Auth#confirmEmail`, right?

I think the reasoning why this isn’t here yet has been that the password reset process should not be streamlined so much that it can easily be used for “login via email”, without remembering the password, and using the reset for every single login. But, after all, why not? Perhaps that decision should indeed be up to the individual service using this library.

Typing the new password once more also ensures that it’s not forgotten again right away. But if the user is copying the password between fields, that doesn’t help, anyway.

Until the feature is here, when using `Auth#forgotPassword` and building the link to send to the user, you could include an additional parameter with the email address. When the link is clicked and you use `Auth#resetPassword`, perhaps use `Auth#admin#logInAsUserByEmail` afterwards – but only after a *successful* reset, of course.

**Comment by ocram** [comment]
On the other hand, [here](https://github.com/delight-im/PHP-Auth/issues/193), we already discussed returning the email address from `Auth#resetPassword`. So that would help with your use case as well.

But that would still only be one part of the solution, since you need either the password or `Auth#admin#logInAsUserByEmail` to complete the login. Sending or storing the password somewhere is generally dangerous, so that only leaves one solution. And the new (proposed) `Auth#resetPasswordAndSignIn`, of course.

**Comment by ocram** [comment]
Implemented in https://github.com/delight-im/PHP-Auth/commit/d49b35690cac0bbaa8e158840b5c5dee1104ca43 and documented in https://github.com/delight-im/PHP-Auth/commit/dcd893a12cbf9fb9bb64fa966944e88f1963d141

**Comment by tmblog** [comment]
Thank you for this really appreciate it! To update my version is it a matter of just replacing all the files? I take this isn't a major release so can't update via composer.

Cheers

**Comment by ocram** [comment]
You can update to *any* release via Composer :)

Simply running

```bash
$ composer update delight-im/auth
```

should be sufficient.

If you still didn’t want to use Composer, replacing the files would be enough *in this case*, yes.
