### ISSUE TITLE
Error with illuminate/database

### ISSUE THREAD

**Issue by 262926** [delight-im/PHP-Auth#209]
`Fatal error: Uncaught InvalidArgumentException: The database connection must be an instance of either `PdoDatabase`, `PdoDsn` or `PDO` in C:\wamp\www\phpus\vendor\delight-im\auth\src\UserManager.php:90 Stack trace: #0 C:\wamp\www\phpus\vendor\delight-im\auth\src\Auth.php(45): Delight\Auth\UserManager->__construct(Object(Illuminate\Database\Capsule\Manager), NULL, NULL) #1 C:\wamp\www\phpus\index.php(29): Delight\Auth\Auth->__construct(Object(Illuminate\Database\Capsule\Manager)) #2 {main} thrown in C:\wamp\www\phpus\vendor\delight-im\auth\src\UserManager.php on line 90`

**Comment by ocram** [comment]
Thanks!

How did you install this library? Using Composer or manually?

The error occurs because `illuminate/database` is the wrong database component.

**Comment by 262926** [comment]
Using Composer

**Comment by ocram** [comment]
Thanks!

Please take a close look at the following section of the README again:

https://github.com/delight-im/PHP-Auth#creating-a-new-instance

The database instance that you pass to `new \Delight\Auth\Auth($db)` must *not* be of type `\Illuminate\Database\Capsule\Manager`. The README shows how to create the database instance – in several possible ways.
