### ISSUE TITLE
Forgot password: why should you verify the attempt first?

### ISSUE THREAD

**Issue by binoculars88** [delight-im/PHP-Auth#215]
This is more a question rather than a bug:
Why should you go through [step 2](https://github.com/delight-im/PHP-Auth#step-2-of-3-verifying-an-attempt)? I get why it exists, because it allows you to check if everything is OK before trying to change the password, but is the step considered mandatory?

I suppose you can just always display the password form and then on form submit provide information when something didn't work (for example if the token expired)? Or am I missing something here why I shouldn't skip step 2?

**Comment by ocram** [comment]
No, you are right, but including that interim step usually results in a far superior user experience.

I guess your users might not really like coming up with a new password, typing it thoroughly – only to be told the request has already expired.
