### ISSUE TITLE
Login by username and email

### ISSUE THREAD

**Issue by ProfessorZel** [delight-im/PHP-Auth#217]
Hi! Thank you for prefect library. I've got question, documentation https://github.com/delight-im/PHP-Auth#login-sign-in, states that we can login users "with usernames on the other hand, either in addition to the login via email address", but your methods login(), loginWithUsername(), can pass only email OR username at one time, it become difficult to write code without repeats in different catch branches, so developer have to do something bad... go to source code and modify it... make getUserDataByEmailAddress() public, and then he can write something like this:

```
try {
        try{
            $data = $auth->getUserDataByEmailAddress($login,['username']);
            $login = $data['username'];
        }catch (Delight\Auth\InvalidEmailException $e){
            
        }
        
        $auth->loginWithUsername($login, $pass);

        return 1;
    }
    catch .... 
```
How it can be done in more canonical way, and what security issues it can cause?
Thanks for your attention!

**Comment by ocram** [comment]
Thanks for your question and for your appreciation!

What are you actually trying to do? Do you want to receive a pair `(identifier, password)` from the user and then use that to log in, no matter if the identifier is an email address or a username?

There’s probably no need to modify the source code of this library and to change the visibility of any method.

Indeed, the existing methods allow for a login with the email address *or* with the username, but they can be combined to provide the “and”.

**Comment by ProfessorZel** [comment]
Suggestion! For those users who has difficulties with binary logic ;-) can you add an Example for this? I think it is more common way of auth then just by username or email.
Thanks!

**Comment by ocram** [comment]
Well, sure, it’s an excellent question!

The following solution has a downside in that *usernames* must *not* contain the `@` character, or at least they can’t be used for logging in if they include an `@`:

```php
try {
    // if the identifier appears to be an email address
    if (\strpos($_POST['identifier'], '@') !== false) {
        $auth->login($_POST['identifier'], $_POST['password']);
    }
    // if the identifier appears to be a username
    else {
        $auth->loginWithUsername($_POST['identifier'], $_POST['password']);
    }

    echo 'User is logged in';
}
catch (\Delight\Auth\InvalidEmailException $e) {
    die('Wrong email address');
}
catch (\Delight\Auth\UnknownUsernameException $e) {
    die('Unknown username');
}
catch (\Delight\Auth\AmbiguousUsernameException $e) {
    die('Ambiguous username');
}
catch (\Delight\Auth\InvalidPasswordException $e) {
    die('Wrong password');
}
catch (\Delight\Auth\EmailNotVerifiedException $e) {
    die('Email not verified');
}
catch (\Delight\Auth\TooManyRequestsException $e) {
    die('Too many requests');
}
```

The following solution has a different, probably more significant, downside in that roughly half of all login attempts automatically count as a failed login attempt, even if they eventually succeed:

```php
try {
    try {
        $auth->login($_POST['identifier'], $_POST['password']);
    }
    catch (\Delight\Auth\InvalidEmailException $e) {
        $auth->loginWithUsername($_POST['identifier'], $_POST['password']);
    }

    echo 'User is logged in';
}
catch (\Delight\Auth\UnknownUsernameException $e) {
    die('Unknown username');
}
catch (\Delight\Auth\AmbiguousUsernameException $e) {
    die('Ambiguous username');
}
catch (\Delight\Auth\InvalidPasswordException $e) {
    die('Wrong password');
}
catch (\Delight\Auth\EmailNotVerifiedException $e) {
    die('Email not verified');
}
catch (\Delight\Auth\TooManyRequestsException $e) {
    die('Too many requests');
}
```

Does that help?
