### ISSUE TITLE
Login-LogOut

### ISSUE THREAD

**Issue by rsnbusa** [delight-im/PHP-Auth#218]
Hi everybody.

If I have 2 scripts, one for login and another for logout. Question is how do I identify who is logging out? 

 $auth->logOut(); ??? To  whom is it referring? No userId or email or anything.

When login     $auth->login($user, $passw); does it return any variable to save/cookie it?

Regards.

**Comment by ocram** [comment]
This library uses [sessions](https://www.php.net/manual/en/intro.session.php) to track who is signed in.

Thus you can log in in your first script. Browse around your site as an authenticated user in a second script. And log out in a third script. The second and third script will each know who is signed in by looking at the session information.

Does that help?

**Comment by rsnbusa** [comment]
Yes thanks. I presume that "Browse around on other scripts" means one should ask in every script " if ($auth->isLoggedIn()) {..."?

Regards.

**Comment by ocram** [comment]
Yes, that’s correct. If you want to know if the user is (still) signed in (in another script), you have to use that check.
