### ISSUE TITLE
Embedded MCU interface

### ISSUE THREAD

**Issue by rsnbusa** [delight-im/PHP-Auth#219]
Hi All. Hope all well.

Im calling the "login.php" from an MCU (esp32) which validates correctly registered users. I presume that in its answer, there is a header (unknown name) that must be preserved during the whole "session". When sent a Logout the answer is "User not logged in" which could be that there is no "session" header. I have to create everything from scratch so i need to know all reureid headers.

Please some help.

RSN

**Comment by ocram** [comment]
Thanks for your question!

So you want to make this library work in a non-browser context, e.g. on embedded devices (or via a CLI), right?

The main task would be to make the library work *without cookies*.

The HTTP headers you’re looking for are mainly `Set-Cookie`, sent by the server, and `Cookie`, sent by the client.

If you don’t want cookies, you need something else to enable *sessions*, i.e. usually to transfer and manage your session identifier. Or you need to authenticate on every single request. Which do you want?

Does that help?

**Comment by Undefined-Variables** [comment]
Yeah @ocram is spot on. You'll have to invent a way to store cookie data as authenicaion on every request is not ideal. Which ever way you look at this its not going to be simple.

**Comment by ocram** [comment]
Again, most features should work fine, but logging in and keeping a session is something that isn’t possible without cookies or an alternative means of keeping track of the session identifier.

What we could do, however, is adding a method named `Auth#once` (or similar) which verifies your credentials (i.e. authenticates the user, as with a login) but without establishing a persistent authenticated state that is kept in a session. So you would have to call `Auth#once` (or similar) on every request.
