### ISSUE TITLE
customizable password requirements and enforcement?

### ISSUE THREAD

**Issue by Tchayka** [delight-im/PHP-Auth#22]
I may have missed something in the documentation but where and how is this feature implemented?
I guess I could validate passwords myself before but I see there is a catch for InvalidPasswordException, however I didn't see where to customize password requirements or where the default requirements are defined.

Any help would be appreciated as I'm trying to use this authentication system for a website.
Thanks.

**Comment by ocram** [comment]
Thanks! That aspect has absolutely been thought of but we decided that letting everyone wrap their own checks for custom requirements around the usage of this library is probably the easiest solution.

Do you see any specific problem with that solution? Or did you just want to check whether your approach is indeed the recommended one? In the first case, please let us know about situations where an alternative solution could be more convenient. In the latter case, please go ahead and just implement your own checks, wrapped around the calls to this library. That's what we're doing as well.

**Comment by Tchayka** [comment]
Thanks for the quick answer.

I have no problem with that solution and I actually like the fact that this project stays focused on its core parts. I was merely concerned about the possibility that there might already be password requirements checks that I missed in the source code.
It would maybe clear up any misunderstanding if the 'features' part of the documentation rephrased that point about password requirements customization.

**Comment by ocram** [comment]
No, there aren't any built-in checks for password requirements, apart from the basic check of whether a password has actually been entered. So what you wanted to do is the correct way to do it, just wrap your own checks around the calls to `register`, `changePassword` and `resetPassword`.

Regarding the README, you're right, that was indeed misleading. Thus, the "Features" section has been removed in https://github.com/delight-im/PHP-Auth/commit/dc233d9d46a8519fefd7264a18e48b2ed2d03ed2 and a new section "Custom password requirements" has been added in https://github.com/delight-im/PHP-Auth/commit/0fb653d6e08fb99b1106089283799281af244b63 which should be more clear now.

Thank you!
