### ISSUE TITLE
skip email verification not working

### ISSUE THREAD

**Issue by pandastreams** [delight-im/PHP-Auth#223]
Hi there,

I am trying this to skip email verification

$auth->register($_POST['email'], $_POST['password'], $_POST['username'])

and logging in through
 $auth->login($_POST['email'], $_POST['password'],$rememberDuration);

But its not working it still says email not verified why?

**Comment by ocram** [comment]
Thanks!

Are you sure the user you’re trying to sign in as with `Auth#login` is the user from the previous `Auth#register` call?

What version of this library are you using?

Could you look at your database table `users` and use `Auth#register` again to create a new account, looking at the `verified` field of the record that will be created?
