### ISSUE TITLE
Is it possible to use this with MS SQL?

### ISSUE THREAD

**Issue by mrohdem** [delight-im/PHP-Auth#224]
I tried setting up Microsoft SQL tables to match as best I could, but when I attempt to create a user, I get: PHP Fatal error:  Uncaught PDOException: SQLSTATE[IMSSP]: The given attribute is only supported on the PDOStatement object. in C:\inetpub\wwwroot\vendor\delight-im\db\src\PdoDatabase.php:544

**Comment by ocram** [comment]
Thanks!

Unfortunately, at the moment, only MySQL, MariaDB, PostgreSQL and SQLite are supported.

You could try to make it work with MS SQL, but that would require changes to the code. I’m afraid it will also require changes to the database component, to be found in the `vendor/delight-im/db` directory.

If you could make it work without too many changes, and while also keeping compatibility with the other database systems, we could certainly merge the changes back here.

**Comment by mrohdem** [comment]
Thanks for the response.  My skills aren't at that level, but maybe someone will come along at some point and make these modifications.

**Comment by ocram** [comment]
Sure, that could happen. Sorry there’s no better solution right now.

In the meantime, perhaps you can also give SQLite a chance, or one of the other systems, if that works for your use case.

**Comment by thedwmss** [comment]
I did this about a month ago, its not perfect but works as intended with MS SQL. Will put it in a doc and post.

**Comment by mrohdem** [comment]
> I did this about a month ago, its not perfect but works as intended with MS SQL. Will put it in a doc and post if you still need it.

That would be great!
