### ISSUE TITLE
Warning: A non-numeric value encountered when a user has no roles and we call doesUserHaveRole with a roles_mask column type TEXT

### ISSUE THREAD

**Issue by khalyomede** [delight-im/PHP-Auth#227]
## Description

A warning raises when calling `->doesUserHaveRole()` method on a user that have no roles in the "roles_mask" column of the "users" table.

## Reproduce the issue

1. Have a users table with a "roles_mask" column as TEXT
2. Register a new user (don't add him roles)
3. Call this method

```php
use Delight\Auth\Auth;
use Delight\Auth\Role;

$auth = new Auth(new PDO("sqlite:my/database.sqlite"), $_SERVER["REMOTE_ADDR"], null, false);

if (!$auth->admin()->doesUserHaveRole($auth->getUserId(), Role::ADMIN) {
  // By checking this if statement, the warning occurs
}
```
4. See the error `Warning: A non-numeric value encountered in C:\Users\khalyomede\test-auth\vendor\delight-im\auth\src\Administration.php on line 305`

## Expected behavior

To not raise a warning if the user has no roles.

## Solutions suggested

I dived into `src/Administration.php:305`, and by changing the code from this:

```php
public function doesUserHaveRole($userId, $role) {
  // ...
  return ($rolesBitmask & $role) === $role;
}
```

To this:

```php
public function doesUserHaveRole($userId, $role) {
  // ...
  return ((int) $rolesBitmask & $role) === $role;
}
```

The error no longer displays.

## Alternatives solutions

Recreate the "roles_mask" column as INTEGER and a default value to 0.

**Comment by khalyomede** [comment]
Did not used the migration script available in the documentation, my bad!

**Comment by ocram** [comment]
No problem, thanks for your perfect report and for sharing your solution!
