### ISSUE TITLE
Learning 

### ISSUE THREAD

**Issue by cometolearn-web** [delight-im/PHP-Auth#234]
Hello dear i wnat to learn this and my issue is may be small but i am new in this field 
i download the composer database created.
now i just use first code which is to check the email validation 
i declare $auth = new \Delight\Auth\Auth($db); instance 
before the code 
but it show me
Message: Class 'Delight\Auth\Auth' not found

**Comment by ocram** [comment]
1. Is there both a `composer.json` and a `composer.lock` in the main directory of your project?
 2. Is there a folder named `vendor`, with a subfolder `delight-im`, again with a subfolder `auth` in the main directory of your project?
 3. Did you include the line `require __DIR__ . '/vendor/autoload.php';` and does it execute without problems?
