### ISSUE TITLE
MyISAM vs InnoDB

### ISSUE THREAD

**Issue by arunagirinathar** [delight-im/PHP-Auth#236]
This is a question & not an issue --

Is there any specific reason for using the MyISAM storage engine ? If not, can we switch the tables to use InnoDB instead ? The reason being, I would like to enforce f-key restrictions on other tables which reference the`id` from the `users` table; like for example a profile table to store user preferences.

Thank you.

**Comment by perfaram** [comment]
Was wondering the same – but I'm wondering if it's because of the locking behavior of MyISAM ?

**Comment by ocram** [comment]
Thanks!

As for MyISAM/InnoDB, please see https://github.com/delight-im/PHP-Auth/issues/144 and https://github.com/delight-im/PHP-Auth/issues/137.

With regard to *internal* foreign keys within the scope of this library and its tables, see https://github.com/delight-im/PHP-Auth/issues/86.

And finally, when it comes to *custom* foreign keys between the tables and columns used by this library and your own tables and columns – absolutely, please go ahead with that.
