### ISSUE TITLE
isLoggedIn not persistent

### ISSUE THREAD

**Issue by T0mAl3x** [delight-im/PHP-Auth#237]
Hello! I'm having problems checking if the user is logged in.
                $this->auth->login($username, $password);
                if ($this->auth->isLoggedIn())
                    return [
                        'status' => 'ok'
                    ];
                return 'Something went wrong';
    
Here the  isLoggedIn returns true which is OK. But when I redirect to another page...

    public function index() {
      // Check if user is logged in
      // else redirect to LogInPage
      $db = new Database;
      $auth = new \Delight\Auth\Auth(
        $db->getPDO(), null, null, false, 60);
      if (!$auth->isLoggedIn()) {
        redirect('users/login');
      }
      
      editPath(null, "reset");

      $result = $this->pagesModel->sendCommand(123456, "EXPLORE", "/");
      setSendedCmdId($result[0]->ID);
      
      $pathsError = '';
      // if (!$result) {
      //   $pathsError = 'There was a problem when sending the command';
      // }

      $data = [];
     
      $this->view('pages/index', $data);
    }
...
In the index method I recreate de auth instance and when I call isLoggedIn() it returns false.

**Comment by T0mAl3x** [comment]
It worked eventually. I think it was a session desync.

**Comment by ocram** [comment]
No problem. Thanks for letting us know!
