### ISSUE TITLE
Setting the roles Question

### ISSUE THREAD

**Issue by Dr-Nio** [delight-im/PHP-Auth#238]
Looking at the documentation of this wonderful and beautiful package 
 can see how to check for role
my issue now is how do i set the roles from the signup process?
Thank you

**Comment by eypsilon** [comment]
> my issue now is how do i set the roles from the signup process?

something like

```php
$auth = new \Delight\Auth\Auth($db);
$defaultRole = \Delight\Auth\Role::CONSULTANT;

// register the new user and get the new ID to work with it
$userId = $auth->register($email, $pass, $username); 

// and finally, set the desired role for the new registered User, eg: CONSULTANT
try {
    $auth->admin()->addRoleForUserById($userId, $defaultRole);
} catch (\Delight\Auth\UnknownIdException $e) {
    // ring the alarm
}
```

https://github.com/delight-im/PHP-Auth#assigning-roles-to-users

**Comment by Dr-Nio** [comment]
Oh! Okay, Good, fairly simple but now how do also send email verification token to mail?

**Comment by ocram** [comment]
@eypsilon Thanks for giving the perfect solution!

@Dr-Nio See @eypsilon’s solution above. The fact that the callback for sending the verification token has been left out there does not mean you cannot use it as usual. So, to answer your second question from your last comment, just use the solution given above with the normal verification callback as shown in the README: https://github.com/delight-im/PHP-Auth#registration-sign-up

Hope that helps!

**Comment by eypsilon** [comment]
> Oh! Okay, Good, fairly simple but now how do also send email verification token to mail?

If you want to get `$selector` and `$token` out of the closure for later use, you can `use(&reference)`

```php
<?php

// ... do all necessary stuff, eg. set $email, $pass, $username, etc.

// initialize data container
$verify = [
    'selector' => false,
    'token' => false
];

try {
    // through the ampersand (&) in use(&$verify) you can set variables as references, which means, you can 
    // manipulate the variable within functions or closures and changes will change the reference, too
    $userId = $auth->register($email, $pass, $username, function($selector, $token) use(&$verify) {
        $verify = [
            'selector' => $selector,
            'token' => $token
        ];
    });
} catch (\Delight\Auth\InvalidEmailException  $e) {
    // there are more Exeptions for $auth->register(), catch them all
}

// make sure you got what you need and build the URL
if ($verify['selector'] AND $verify['token']) {
    $verifyUrl = "https://example.com/verify?selector={$verify['selector']}&token={$verify['token']}";
} else {
    // ring the alarm
}
```

**Comment by ocram** [comment]
Excellent point, thanks, @eypsilon!

**Comment by eypsilon** [comment]
Gladly, and i've to improve my English anyhow, so :)
