### ISSUE TITLE
Setting Role and Sending Verification Email question

### ISSUE THREAD

**Issue by Dr-Nio** [delight-im/PHP-Auth#240]
Looking at the documentation of this wonderful and beautiful package
can see how to check for role
my issue now is how do i set the roles and also send the verification email at the same time from the signup process?
Thank you

**Comment by ocram** [comment]
See https://github.com/delight-im/PHP-Auth/issues/238 and https://github.com/delight-im/PHP-Auth/issues/239

Any remaining questions?

**Comment by Dr-Nio** [comment]
I need to understand if the package generates the parameters for the url  to be sent to the newly registered account?

**Comment by Dr-Nio** [comment]
Oh, okay
Seen #238 and #239

Now i understand
Thank you, you are good at this
