### ISSUE TITLE
Database instance

### ISSUE THREAD

**Issue by vmaysov** [delight-im/PHP-Auth#241]
Hello! I'm trying to execute method auth->register, but getting error «Uncaught InvalidArgumentException: The database connection must be an instance of either `PdoDatabase`, `PdoDsn` or `PDO`» in vendor\delight-im\auth\src\UserManager.php on line 88.

I have a instance of PDO in my own singleton class:

class Db
{

    private static $instance = null;

    private function __construct() {}

    private function __clone() {}

    public static function getInstance() {
        if (!self::$instance) {
            try {
                self::$instance = new PDO('mysql:dbname= ... etc

and require it as $this->auth = new \Delight\Auth\Auth($this->dbh);

where 
$this->dbh
is a instance of PDO. what am I doing wrong?

**Comment by vmaysov** [comment]
sorry, i solved that

**Comment by ocram** [comment]
Thanks, no problem :)
