### ISSUE TITLE
Does it work with PSR-7 frameworks?

### ISSUE THREAD

**Issue by gotzmann** [delight-im/PHP-Auth#245]
I'm trying to use PHP-Auth with [Comet PHP framework](https://github.com/gotzmann/comet) and can't understand how to enable COOKIE / SESSION management with PSR-7 based HTTP requests and responses.

**Comment by ocram** [comment]
Thanks!

Right now, this library does not use `Psr\Http\Message\RequestInterface` and/or `Psr\Http\Message\ResponseInterface` but instead accesses the request and response data directly via the built-in PHP data structures and functions.

For example, when logging in, the HTTP response header for the session cookie is written directly, as with `\header(...)` or `\setcookie(...)`, not offered to an interface. Is the latter what you would request?

**Comment by gotzmann** [comment]
Thanks for the answer!

Since I did not find the way to use PHP Auth as is and still really like it, I've revorked it.  No setcookie / header stuff at all, only Session abstraction:

https://github.com/gotzmann/auth
