### ISSUE TITLE
hashing mechanism

### ISSUE THREAD

**Issue by acodispo** [delight-im/PHP-Auth#25]
What sort of hashing mechanism is being used in php-auth?

Thanks for your time!

**Comment by ocram** [comment]
Thanks for this important question!

Details regarding password hashing have been added to the README now: https://github.com/delight-im/PHP-Auth/commit/7834455e1691d26d3a77d870c2a3e2c0dac5dd46

Hope that helps!

**Comment by acodispo** [comment]
Great, that's what I thought, but great to have it confirmed! Thanks!
