### ISSUE TITLE
"Too many requests" for all users on forgotPassword even with no prior attempts

### ISSUE THREAD

**Issue by triumphhub** [delight-im/PHP-Auth#255]
Hello,

I get a "Too many requests" for all users on forgotPassword even with no prior attempts. The user_resets table is empty.
Another unexpected behaviour is when I don't set an email address variable it returns "Invalid email address" whereas I would expect this to be an exception. Below is my test code:

`	//Database connection
        include_once('../####/######.php');
	require '../vendor/autoload.php';
	$auth = new \Delight\Auth\Auth($login);
	$_POST['email'] = '####@####.com';
	
try {
    $auth->forgotPassword($_POST['email'], function ($selector, $token) {
        echo 'Send ' . $selector . ' and ' . $token . ' to the user (e.g. via email)';
    });

    echo 'Request has been generated';
}
catch (\Delight\Auth\InvalidEmailException $e) {
    die('Invalid email address');
}
catch (\Delight\Auth\EmailNotVerifiedException $e) {
    die('Email not verified');
}
catch (\Delight\Auth\ResetDisabledException $e) {
    die('Password reset is disabled');
}
catch (\Delight\Auth\TooManyRequestsException $e) {
    die('Too many requests');
}`

Any help is much appreciated.

**Comment by ocram** [comment]
Thanks a lot, @eypsilon!
