### ISSUE TITLE
Is there a function to check if new registration passwords match?

### ISSUE THREAD

**Issue by twointum** [delight-im/PHP-Auth#256]
Or should I do that part myself? Thanks!

**Comment by eypsilon** [comment]
The API by itself just expects a value to set as password. This is something you can handle best in your UI. You also don't need a separate input field for that, you can provide a button for toggling type "password"  to "text".

**Comment by ocram** [comment]
Yes, you can add a second input field for the password, and then wrap the call to `Auth#register` in something like this:

```php
$pw = \trim($_POST['password']);
$pwConfirmation = \trim($_POST['password-confirmation']);

if ($pw === $pwConfirmation) {
    // TODO ...
}
```

Using just one input field for the password and instead offering a “make password visible” (and the reverse) button, as @eypsilon suggested, is another solution. Whatever you (or your requirements) prefer.
