### ISSUE TITLE
Authenticator is blank

### ISSUE THREAD

**Issue by timmya3** [delight-im/PHP-Auth#257]
I added a second MS account on my computer and was receiving two codes when I selected authenticator. I needed to remove that so I removed the extension from chrome. When I re-added it Authenticator is now blank with no codes. I added the second person to a new computer and when I hit authenticator it is also blank? This is all done on Chrome.

**Comment by ocram** [comment]
This doesn’t seem to be related to this library, as Microsoft Authenticator or Google Authenticator, or Microsoft accounts, are not really related to this project.
