### ISSUE TITLE
Composer package isn't set up to update automatically

### ISSUE THREAD

**Issue by CodeByZach** [delight-im/PHP-Auth#259]
<img width="1224" alt="Screen Shot 2021-08-20 at 11 23 07 PM" src="https://user-images.githubusercontent.com/20159826/130308960-8fbb4822-ab3c-42e6-9be0-75ecedf8bb1b.png">

**Comment by ocram** [comment]
Thanks!

This is no problem, as we reliably update it there via other means.

But let’s try both. Can’t be worse, but perhaps better when one fails.

Should be fixed now.
