### ISSUE TITLE
Is there a way to change a username?

### ISSUE THREAD

**Issue by bashonly** [delight-im/PHP-Auth#261]
Just wondering: is there any way to change a user's username as an administrator, or would it have to be done by manual SQL query (and if that's the case: which tables need to be updated)?

**Comment by eypsilon** [comment]
No, that's indeed missing in the API, but it's not a big thing anyway, with PDO, you can do something like

```php
// "users" is the table that contains the Username
$exec = $this->db->prepare('UPDATE users SET username = ? WHERE id = ?');
$exec->execute(['New Username', 15]); // if true, username has been updated
```

**Comment by bashonly** [comment]
Thanks eypsilon. 

This library rules, btw.

**Comment by upintheairsheep** [comment]
Hello, could you address https://github.com/yt-dlp/yt-dlp/issues/5037 by adding support for TikTok comments and replies from the api? TikTok comments have been requested by both me, and another user( https://github.com/yt-dlp/yt-dlp/issues/1445 ), and would be useful for archiving tiktok videos and doing data science with them.

**Comment by lewweiming** [comment]
You'll mostly likely need to update the $_SESSION['auth_username'] after a username change as well since the getUsername function is based on session variables and not table values.

```
// Delight PHP
public function getUsername() {
--
if (isset($_SESSION) && isset($_SESSION[self::SESSION_FIELD_USERNAME])) {
return $_SESSION[self::SESSION_FIELD_USERNAME];
}
```
