### ISSUE TITLE
How to send email ?

### ISSUE THREAD

**Issue by johntunnel** [delight-im/PHP-Auth#263]
Hi
Have beginner question: 
How to actually send verification email with url containing token and selector?
I did not see this part included in the code. Can you suggest some other script to send email ?

**Comment by arunagirinathar** [comment]
You need to use mail library like [PHPMailer](https://github.com/PHPMailer/PHPMailer) or something similar.

**Comment by ocram** [comment]
Thanks @arunagirinathar!

@johntunnel Yes, PHPMailer or a similar library is fine. A note listing such libraries has been added to the README now: https://github.com/delight-im/PHP-Auth/commit/0d240e4322da27b09de2dee818328c9b208ee61f
