### ISSUE TITLE
How to generate selector ?

### ISSUE THREAD

**Issue by johntunnel** [delight-im/PHP-Auth#264]
Hi
I would like to know how I can generate selector for verification URL which is sent to user.

**Comment by ocram** [comment]
You don’t need to generate these yourself, as they are generated for you by the library.

You send the email or SMS in the

```php
function ($selector, $token) {
    // ...
}
```

callback, and that’s where you receive the generated values in the two parameters. Just use these parameters in your URL (e.g. via string concatenation).

Or do you want to generate such tokens yourself for other purposes? Then `UserManager::createRandomString(...)` is for you.
