### ISSUE TITLE
Remember me not working

### ISSUE THREAD

**Issue by EdwinHuijsing** [delight-im/PHP-Auth#266]
On this moment i am building a simple demo site to learn how PHP-Auth is working.
PHP-Auth version v8.3.0 install with composer and php 8.0.12 (Docker)

I have created a user and can login, `$auth->isLoggedIn()` is true and the value for `auth_logged_in` in the session is true.

If i pass the remember me value `(int) (60 * 60 * 24 * 365.25)` then the table `users_remembered` is updated and the value is stored in a cookie, but the session value for key `auth_remembered` is false. If i run the test `$auth->isRemembered()` then it is false.

What am i doing wrong?

see [pastbin](https://pastebin.com/cnC8yqAD) for the login form and processing code i am using.

**Comment by eypsilon** [comment]
You have to end the current SESSION to become recognizable. 

Login with "remember" turned on and restart your browser. Or delete the "PHPSESSION" manually.

**Comment by EdwinHuijsing** [comment]
Thanks for the help.

It works now.
I thought that it would show `true` if have the "remember me" enable while logging in, but instead it shows `true` if you have used "remember me" cookie to "login".

**Comment by ocram** [comment]
Yes, this indicates whether the user has been logged in automatically using that feature, not whether that feature is generally active.

See also:
 * https://github.com/delight-im/PHP-Auth#checking-whether-the-user-was-remembered
 * https://github.com/delight-im/PHP-Auth#reconfirming-the-users-password

(Thanks again, @eypsilon!)
