### ISSUE TITLE
Fatfree Framework Issue

### ISSUE THREAD

**Issue by jobasc0** [delight-im/PHP-Auth#275]
Hi, i am very new to php and i am trying to use F3 (fatfree framework) with Delite-im/Php-Auth and i am getting this error on my controller.php page.
Undefined array key "email" 
This is the code.
  public function login()
    {
        // $db = new \PDO('mysql:dbname=my-database;host=localhost;charset=utf8mb4', 'my-username', 'my-password');
// or
// $db = new \PDO('pgsql:dbname=my-database;host=localhost;port=5432', 'my-username', 'my-password');
// or
// $db = new \PDO('sqlite:../Databases/my-database.sqlite');
// or
$db = \Delight\Db\PdoDatabase::fromDsn(new \Delight\Db\PdoDsn('mysql:dbname=wapknhmx_igni173;host=localhost;charset=utf8mb4', 'wapknhmx_igni173', '2m8Ds@]5t1@zpS.-'));
// or
// $db = \Delight\Db\PdoDatabase::fromDsn(new \Delight\Db\PdoDsn('pgsql:dbname=my-database;host=localhost;port=5432', 'my-username', 'my-password'));
// or
// $db = \Delight\Db\PdoDatabase::fromDsn(new \Delight\Db\PdoDsn('sqlite:../Databases/my-database.sqlite'));
$auth = new \Delight\Auth\Auth($db);
        try {
    $auth->login($_POST['email'], $_POST['password']);
    echo 'User is logged in';
}
catch (\Delight\Auth\InvalidEmailException $e) {
    die('Wrong email address');
}
catch (\Delight\Auth\InvalidPasswordException $e) {
    die('Wrong password');
}
catch (\Delight\Auth\EmailNotVerifiedException $e) {
    die('Email not verified');
}
catch (\Delight\Auth\TooManyRequestsException $e) {
    die('Too many requests');
}
        $ms->addMessageTranslated('success', 'WELCOME', $currentUser->toArray());
        // Set redirect, if relevant
        $redirectOnLogin = $this->ci->get('redirect.onLogin');
        return $redirectOnLogin($request, $response, $args);
    }
}
Please help. i will be very greatful i can get a full working login/register page example.
Thanks

**Comment by zfarkas88** [comment]
Hi,

it seems your login form not contain email field or the name is not exactly email.

**Comment by jobasc0** [comment]
@zfarkas88 the code is locate at mine controller page AuthController.php and form will be at login.html . Please help. how do i go about this?

**Comment by zfarkas88** [comment]
Github is not the appropriate place to discuss your problem beacuse It is not a PHP-Auth issue.

I'm not familiar with the mentioned framework.  What is in your login.html?

**Comment by jobasc0** [comment]
<form method="post">
							<div class="form-group">	
							  <input type="text" id="input" required="required"/>
							  <label class="control-label" for="email">Email</label><i class="mtrl-select"></i>
							</div>
							<div class="form-group">	
							  <input type="password" required="required"/>
							  <label class="control-label" for="input">Password</label><i class="mtrl-select"></i>
							</div>
							<div class="checkbox">
							  <label>
								<input type="checkbox" checked="checked"/><i class="check-box"></i>Always Remember Me.
							  </label>
							</div>
							<a href="#" title="" class="forgot-pwd">Forgot Password?</a>
							<div class="submit-btns">
								<button class="mtr-btn signin" type="button"><span>Login</span></button>
								<button class="mtr-btn signup" type="button"><span>Register</span></button>
							</div>
						</form>

**Comment by ocram** [comment]
Thank you, @maietta and @zfarkas88 !
