### ISSUE TITLE
periods in email addresses

### ISSUE THREAD

**Issue by Peabo83** [delight-im/PHP-Auth#293]
Hello!

Use case: User X registers with the email address MyEmail@address.com. User X then registers a second account using My.Email@address.com. These two email addresses, which are functionally the same address end up generating two different accounts.

Obviously stripping out the periods before submitting the email to $auth->register and $auth->login would correct this issue, however I was wondering if there was some kind of integrated fix for this that I'm not finding in the documentation.

Thanks for taking a moment to read my question!

**Comment by acicali** [comment]
I'm sure you're already aware, but only certain email providers ignore periods in the local part. Gmail may ignore periods, but Yahoo doesn't. Also, Gmail (and likely others) support plus addressing... "johndoe+randomLabel@gmail.com", "johndoe+somethingElse@gmail.com" both go to the same address.

Trying to "canonicalize" these various forms might prove futile. Perhaps just for Gmail (the dominant provider) it might be worth stripping periods and plus addresses.

**Comment by ocram** [comment]
This has been answered/addressed perfectly already. If you feel you want canonicalization/grouping of email addresses that go to the same inbox, you may implement this yourself, per provider, e.g. as one separate function, and use it to pre-process all email addresses that you pass to this library.
