### ISSUE TITLE
 Is compatible with php 8.1 ?

### ISSUE THREAD

**Issue by NicolasReitin** [delight-im/PHP-Auth#294]
Hello, and thanks in advance for your attention on this!

This PHP-Auth is compatible with php 8.1? 
I couldn't find the information.

Thanks for taking a moment to read my question!

**Comment by Peabo83** [comment]
I've got this working in a PHP8.2 build, should work fine with 8.1 as well.

**Comment by NicolasReitin** [comment]
Thanks for these informations!!
