### ISSUE TITLE
The best way to send a re-confirmation email?

### ISSUE THREAD

**Issue by scifinder** [delight-im/PHP-Auth#297]
Hello!

I can't think of a better algorithm for actions when confirming an email.
If the user has NOT confirmed his email, but at the same time makes an attempt to login, he will receive the following exception: `\Delight\Auth\EmailNotVerifiedException`. Here I can display a message about the need to confirm the email. But I can't think of a better way to resend a confirm email in this case. And if the user entered his address incorrectly during registration and the confirmation letter sent to a stranger - what should I do? Obviously, the user needs to be given the opportunity to change their email address here, but we can't do that until the email is confirmed, right?

I will be glad of any ideas. Thanks!

**Comment by eypsilon** [comment]
A "change" is not necessary at this point, force the User to register with a valid Email, don't work around it. Unconfirmed Emails expire, so you will not break anything there or make unconfirmed Emails useless forever. Changing the Email makes only sense with confirmed email addresses, not while in the registering process.

**Comment by scifinder** [comment]
@eypsilon, thank you for your reply! But there is one nuance. In my system, registration is carried out by invitation. After registration, the invitation code is marked as used.
1. Let's imagine that the user simply did not receive a confirmation email. In this case, after logging in, he will see a message with the need to confirm the email address. In principle, if for some reason he did not receive the letter, I can send him the letter again here. Do I understand correctly that I can use the value of the `$_POST['email']` variable taken from the login form for this? In fact, this was my main initial question.
2. Let's say the user made a mistake when entering an email address during registration, and then, when trying to log in, entered the address correctly and, of course, received a message that such an address does not exist. In this case, I need to find out about it somehow and make the invitation code active again. I can't resolve this contradiction for myself yet.

**Comment by scifinder** [comment]
Returning to first question: can I do something like this?

```
try {
    $auth->login($_POST['email'], $_POST['password']);

    echo 'User is logged in';
}
...
catch (\Delight\Auth\EmailNotVerifiedException $e) {
    
    $url = 'https://my-site.com/re-send-confirmation/' . bin2hex( http_build_query( [ 'email' => $_POST['email'] ] ) );
    
    die('Email not verified. <a href="' . $url . '">Click to resend the confirmation email.</a>');
}
...
```

**Comment by scifinder** [comment]
It's a good idea. Thank you for your help! =)
