### ISSUE TITLE
Forget password option

### ISSUE THREAD

**Issue by HeliTeknik** [delight-im/PHP-Auth#3]
I could not see a forget password option, can you please implement it ?

**Comment by mwaclawek** [comment]
You're right, thanks!

It will be added shortly.

**Comment by mwaclawek** [comment]
Password reset has been implemented in https://github.com/delight-im/PHP-Auth/commit/f3ca69010fe83eeb6cebe3c514e7b43c2d961c68, https://github.com/delight-im/PHP-Auth/commit/53e1a5c1fc09a7315e41298dbc1a56b93731ea28 and https://github.com/delight-im/PHP-Auth/commit/31ae1357404e844a512be02b19c149626549f56a.

You might find the updated documentation helpful when using this feature: https://github.com/delight-im/PHP-Auth/commit/d527a82bfa434617a9b96525eac5e62621e27e91
