### ISSUE TITLE
manual installation readme for shared servers that don't allow composer?

### ISSUE THREAD

**Issue by snakeyengel** [delight-im/PHP-Auth#31]
For the many thousands of us working on shared servers across many hosting sites, composer isn't installed or allowed without upgrading to VPS or dedicated boxes. It would be most awesome if a detailed readme could be made explaining how to install PHP-Auth manually.  Obviously, the DB is easy part, although I love your idea of a table prefix option.

Would this be possible? Many thanks for your awesome work!

**Comment by ocram** [comment]
Thanks for your feedback and appreciation!

*One* of the great things about Composer is that it doesn't actually require any additional software or configuration on your server. It is sufficient to install and run Composer *locally* only, i.e. on your workstation that you use for development.

Composer stores *all* data that is relevant to your project in only three places: The two files `composer.json` and `composer.lock` (which you should add to version control) and the folder `vendor` (which you should *not* add to version control). The latter directory is the only additional piece required for your application to work on your server. Thus do you need Composer on the server? No, just run Composer locally to generate the `vendor` folder and upload that folder to the server. It's as simple as that.

Could you give that a try?

Making this library work without Composer is possible with some additional effort on part of the developers and a much more difficult update process for users. But I really don't think it's required, or worth it, anyway. Most problems with Composer simply stem from a lack of familiarity with Composer and a lack of understanding how it (really) works. Both are understandable, but can be "fixed" easily :)

**Comment by snakeyengel** [comment]
Thanks for the response! I will absolutely give it a try. Cheers!

**Comment by snakeyengel** [comment]
That worked, however, it wants to use the mysqlnd driver for PDO and it doesn't look to be enabled or compiled in for mysql/mysqli. Is there a way to use libmysqlclient instead?

**Comment by ocram** [comment]
Thanks for trying – and I'm happy to hear that it actually worked!

As a general rule, in the future, yes, please just close the old issue (if solved) and open a new one if you have another question. But this time, let's finish the discussion here.

Indeed, there was no way to use this library with the old MySQL Client Library (libmysqlclient), but now there is. You should just have to update your version of this library using Composer:

```
$ composer update delight-im/auth
```

After that, it should work fine with the old driver. For now, at least. This cannot be guaranteed for the future. See https://github.com/delight-im/PHP-Auth/issues/18.

**Comment by snakeyengel** [comment]
Brilliant! That did the trick, mate! I've been out of coding, in general for more than a year, and I've decided to get back into it and this one sticking point of authorization (which is not trivial) has always been an impediment to getting this one site working. Many, many thanks!!!

**Comment by ocram** [comment]
No problem, glad I could help!
