### ISSUE TITLE
Cookie expire problem

### ISSUE THREAD

**Issue by HeliTeknik** [delight-im/PHP-Auth#4]
I have problem at remember me function. Can you please show me the exact place to set an non-expiring cookie for the login ?

**Comment by ocram** [comment]
As shown in the README, a normal login would be done like this:

```php
$auth->login($_POST['email'], $_POST['password']);
```

Now if you want to keep the user logged in, just pass `true` as the third parameter. You can read the PHPDoc on that method for help.

```php
$auth->login($_POST['email'], $_POST['password'], true);
```

If you want that option to depend on some user-supplied value (e.g. from a "remember me" checkbox in the HTML form for the login), use something like this:

```php
$auth->login($_POST['email'], $_POST['password'], ($_POST['remember'] == 1));
```

It will expire as well, but only [after 28 days](https://github.com/delight-im/PHP-Auth/blob/5c6a71d921fd9a99778e6da218715fbcebc0eafa/src/Auth.php#L372). The session (which is used for simple logins) expires much, much faster, usually.

Does that help?
