### ISSUE TITLE
Password challenge

### ISSUE THREAD

**Issue by rgvy** [delight-im/PHP-Auth#40]
Hello

Just a quick feature suggestion: the ability to challenge a user for a password without proceeding through a complete login process.

For example, imagine that a user is already authenticated because they are remembered. But now the user accesses a "dangerous" or "significant" feature (such as linking a bank account). It would be good to challenge the user for their password again to ensure that it is not an imposter using a shared computer, for instance.

Browsing the internals of `Auth.php` I see that this can be done by `password_verify($password, $userData['password'])`. However, perhaps there is some more reusable logic that may be helpful. Or if the password hashing changes, it would be good to encapsulate it all in one place...

Thx

**Comment by ocram** [comment]
Thank you very much!

You're right about everything, and this is definitely needed. That feature has indeed been envisaged from the beginning, which is why we have `isRemembered` in the first place. But somehow it was forgotten later on.

Will be available shortly!

**Comment by Furentes** [comment]
I'm very interested in this feature! Any information on when this will be available?

**Comment by ocram** [comment]
@Furentes Within the next week!

**Comment by Furentes** [comment]
Awesome! 👍

**Comment by ocram** [comment]
Implemented in:

 * https://github.com/delight-im/PHP-Auth/commit/f56e7e6871a15e402c23c8d6deca26b6f06fc4cf
 * https://github.com/delight-im/PHP-Auth/commit/79ecb85bb6d927058de7fd0fd0877652a6f4c916
 * https://github.com/delight-im/PHP-Auth/commit/d8f21a35fc6fef074ca694522acd221b557aed68

This is available in a new major version, `v6.0.0`, which comes with a few breaking changes. For a guide on how to upgrade, please see the migration notes in `Migration.md`.
