### ISSUE TITLE
Change password without the old password

### ISSUE THREAD

**Issue by Klian** [delight-im/PHP-Auth#41]
Hi,

Is there any way to update the user password without the old password?

**Comment by ocram** [comment]
Thanks!

Do you want to do this as a user (i.e. let the user do this on their own) or as an administrator?

For the first case, the decision to require the old password as well has been intentional. But perhaps there might be some use cases where this is not required.

**Comment by Klian** [comment]
Hi ocram,

Yes, I want to do this as a user.

I've seen the function updatePassword inside Auth.php :)

**Comment by ocram** [comment]
Will be available shortly, using a small wrapper around `updatePassword`. Thanks!

**Comment by fdiengdoh** [comment]
I wasn't sure if this would be secure? but isn't password update a sensitive access? What if someone use rememberme by mistake on a public computer and somebody change the password without needing to input the old password?

**Comment by fdiengdoh** [comment]
But as an admin it sound logical.

**Comment by ocram** [comment]
@fdiengdoh You're absolutely right. That's why the current method for changing the password still requires the old password to be entered. With the new method added, the old one will still be the recommended one and the default.

**Comment by ocram** [comment]
Implemented in:

 * https://github.com/delight-im/PHP-Auth/commit/1800525b51468c6d8b20a66562c9da71951d408f
 * https://github.com/delight-im/PHP-Auth/commit/62c5fab1ad784a78f92caca4ae430054bbda1560
 * https://github.com/delight-im/PHP-Auth/commit/7272fbb9a8a8092fdec45f5d53f1b428e1d8af61
 * https://github.com/delight-im/PHP-Auth/commit/91f50a80bb1d7e079665667178d40a4ca30c9029

This is available in a new major version, `v6.0.0`, which comes with a few breaking changes. For a guide on how to upgrade, please see the migration notes in `Migration.md`.
