### ISSUE TITLE
need session after log out

### ISSUE THREAD

**Issue by acodispo** [delight-im/PHP-Auth#43]
After logging out, I have some ajax stuff that needs session variables in order to function.

Is it normal to force a page reload after using `$auth->logout();`? Or is there a preferred way to regenerate the session?

Let me know if you need more info. Thanks in advance!

**Comment by ocram** [comment]
Well, if you do the logout via a POST request (without AJAX), it may [make sense](https://en.wikipedia.org/wiki/Post/Redirect/Get) to do a redirect afterwards. In all other cases, and even with a POST request, it is definitely *not necessary* to do a redirect.

What you might try is calling

```php
\Delight\Cookie\Session::start();
```

right after the call to the `logout` method. Does that help? It it does, that could certainly be incorporated into some new `logoutAndCreateNewSession` method.

**Comment by acodispo** [comment]
Thank you, @ocram we will try that and report back.

**Comment by 32Blahs** [comment]
Acodispo, my extend to PHPAuth fixes this issue. Only auth info is destroyed, the session itself is preserved.

**Comment by ocram** [comment]
@acodispo I probably got that wrong! I thought you only needed an active session (with an empty `$_SESSION` array) for your AJAX requests. But you probably want to retain all your session data as well, right? If so, we'll track that in https://github.com/delight-im/PHP-Auth/issues/47. Otherwise, the fix proposed above should help.

**Comment by acodispo** [comment]
@ocram Great, thanks!

**Comment by ocram** [comment]
New method added, see https://github.com/delight-im/PHP-Auth/issues/47
