### ISSUE TITLE
The registration page keeps loading forever

### ISSUE THREAD

**Issue by elieobeid7** [delight-im/PHP-Auth#46]
register.php

```
<?php 
$pagetitle = 'register';
 require('database_connect.php');

$email = 'aa@a.com';
$password= 'somepassword';
$username='elie';

try {
    $userId = $auth->admin()->createUser($email, $password, $username);
    


    // we have signed up a new user with the ID `$userId`
}
catch (\Delight\Auth\InvalidEmailException $e) {
    // invalid email address
}
catch (\Delight\Auth\InvalidPasswordException $e) {
    // invalid password
}
catch (\Delight\Auth\UserAlreadyExistsException $e) {
    // user already exists
}
 ?>
```

connect.php
```
<?php
require __DIR__ . '/vendor/autoload.php';
use SimpleCrud\SimpleCrud;


/* Connect to a MySQL database using driver invocation */
$dsn = 'mysql:dbname=db;host=127.0.0.1';
$user = 'root';
$password = '';

try {
    $pdo = new PDO($dsn, $user, $password);
    $db = new SimpleCrud($pdo);
    $auth = new \Delight\Auth\Auth($pdo);


} catch (PDOException $e) {
    echo 'Connection failed: ' . $e->getMessage();
}



?>

```

Also tried to edit it to match the one in readme file, same problem. nothing in database. I'm using mariadb, xampp for linux, latest version

**Comment by elieobeid7** [comment]
If you don't reply, how can i trust this library to use it? How does anyone use it?

**Comment by rgvy** [comment]
(Note: I don't represent this project)

Some ideas:
--Server/database configuration issue. That is a common cause of pages hanging/not loading.
--Double check if it's possible to share a single PDO object between SimpleCrud and something else.
--If it's not possible to reuse the PDO, consider using the Delight\Db component included with Auth. It's a very good DB wrapper.
--Use echo statements to find the exact line of code that hangs. Then investigate from there.

I use this framework and can attest that it is quite excellent.

**Comment by elieobeid7** [comment]
the sql included doesn't generate a utf8 table, i changed tables that are created by that libraries to utf8, could that be the problem?

**Comment by rgvy** [comment]
I doubt it. Databases tend to fail quickly

Try to figure out which line of code is causing the problem. Place `echo 'error here';` statements around various code blocks to pinpoint.

**Comment by ocram** [comment]
Thanks for your help, @rgvy!

@elieobeid7 I could not give any better advice than @rgvy has already given, especially with the fourth point (which has been repeated in the second post). Try to track down the exact line where PHP starts hanging. If it turns out that it's indeed an issue with this library, please feel free to re-open this issue.
