### ISSUE TITLE
Change request: role const values

### ISSUE THREAD

**Issue by 32Blahs** [delight-im/PHP-Auth#50]
Last post until I hear back from the project team, promise.

Requesting a breaking change to Roles class. Please can you reorder the CONST so that the values are in numerical order from lowest to highest privilege. Ie: super administrator should be 999, administrator should be 666, and basic user should be 333, and guest should be 1 or whatever.

Doing this will allow my extend to ensure that the admin interface will only grant or edit roles less than or equal to the currently logged in user. This is a standard security control against elevation of privilege - will also allow control of user granting themself additional roles.

Appreciate that users of this library can do this themselves by aliasing the const, but they won't realize the implication of NOT doing this unless it's a) down in the code, b) shown in the docs before the check is added to the admin role grant and remove methods.

Unfortunately this will be a breaking change for anyone who uses the library today, even though it's not actually a code change in itself, it just enables a feature to be implemented.

Might also be a good time to stop using const for roles, and use a database table instead, because the const approach is very limiting for features.

Thanks

**Comment by rgvy** [comment]
The idea behind the roles system in this framework is that they are non-linear. There can be multiple sets of permissions without a set hierarchy. For example, an EDITOR might be able to change textual content of a blog, while a DEVELOPER might be able to change css styling of a blog. In this case, each role shouldn't be allowed to edit the other's data. Of course an admin or super-admin should be able to do it all, but below that, there can be multiple, non-linear permission sets.

Also, the constants were meant as a suggestion. It is advisable to define your own based on your needs.

**Comment by 32Blahs** [comment]
That's fine and I understand that as far as user level roles go. But when you look at the admin roles, the system doesn't have any easy way of preventing elevation of privilege. 

Using your example, an EDITOR may be able to change textual content, and they may also be allowed to make other users CREATORS so the EDITOR can edit their content. 

So, to allow the EDITOR the right to change other user roles (so they can make CREATORS), they have to be given access to the admin() system for role changes.

Example scenario: EDITOR is given access to the admin system. EDITOR registers new user account, and uses the admin() to grant the new user account a super moderator permission. That should never, ever be allowed in an IDAM system.

Here's the problem. If you give a user an admin level role, and provide them with access to the ->admin() system, PHP-Auth will happily let them elevate their role without question. It's up to the calling code to prevent this. That's ok if you only have 1 or 2 admin roles, but if you have more than that it becomes a complex conditional iterator:

```
if(requesting superadmin role)
{
    foreach (<somehow get roles, see below> as $role)
    {
        if(superadmin role does not have greater privileges than $role)
        {
             if(admin->doesUserHaveRole($userid, $role))
             {
                 // User has a role that has greater privileges than the role being requested
                 // therefore it's ok to grant this role
                 admin->addRoleForUserByID(...);
             }
        }
    }
}
```

Core PHP-Auth doesn't have a method that retrieves all the roles (my extend does), so this code isn't even possible with the core lib. 

In addition doesUserHaveRole() makes a DB query every time, so there's a cost to doing this for every role in use.

Contrast this with my suggestion. Order the roles so that those with higher privileges come after those with lower privileges (where admin access is concerned, at least). Now, to test whether a user can grant themselves a role:

```
    // Find the highest const value of roles for user - we can do this somewhere else, eg on login etc
    $arrayOfUserRoles = $Auth->getUserRoles();
    $highestRoleVal = 0;
    foreach($arrayOfUserRoles as $role)
    {
        if($role > $highestRoleVal)
            $highestRoleVal = $role;
    }

// ----------------

    // Now it's 1 line of code to check if user has more privs than the role they're trying to grant
    if($highestRoleVal > $roleRequestedVal)
        // User has high enough privs, grant the role 
    else
        // User is trying an elevation of privilege, deny!
```


Appreciate that PHP-Auth is lightweight and meant to be a base lib, but there are a lot of these gaps in the system. I don't know whether it's because the developers aren't used to thinking about these things in a system security context, or if they chose not to do it to keep the lib tight, but something like this is incredibly simple to implement/prevent just through some planning.

An IDAM system should prevent simple elevation of privilege. The current system is only a valid model if there is one single administrator role, and they are the only role that may access the admin().

**Comment by rgvy** [comment]
I'm not sure you understood my example. Let me rehash:

EDITOR can change textual content, but not css. DEVELOPER can change css, but not textual content. There is no way to determine which of these types of users is "higher". These roles are non-linear -- it's not a simple 1D hierarchy of types of people with increasing importance. EDITORs can only access EDITOR stuff, DEVELOPERs can only access developer stuff. ADMINs could probably access both, and SUBSCRIBERs could probably access neither.

In this case, the framework is leaving it entirely up to the application layer (rather than the framework layer) to determine how to utilize any or all roles. The documentation actively encourages overriding the const values. So you'd have a MyRoles class with any roles and numbers you'd want. From a framework perspective, this is preferable to limiting potential implementors to a 1D permissions/role hierarchy.

As far as one db query per doesUserHaveRole(), I'd recommend using auth->hasRole() for checking the current user's role-- It is cached in the user's session. doesUserHaveRole could be used in an API/DAO layer for data writes only perhaps.

**Comment by 32Blahs** [comment]
Hah, I'm not sure you understood my example! You've mentioned ->hasRole(), but this is a code-level check on the current logged in user via the Auth class method. You also can't do a hasRole() check without using a costly iterator as per my example above.

What I'm talking about is admin management of the system. Imagine PHPAuth was used in developing a Wordpress clone, or similar. Some users will have admin permissions, and some of those admin permissions will necessitate the admin user being able to grant other users some roles.

I completely understand and agree with you on the "user level roles", which should definitely be non-linear. 

What I don't agree with is how any administration level role that can use the PHPAuth admin system is managed, because it is vulnerable to a privilege elevation. 

My suggestion doesn't limit anyone to a 1D heirarchy. It's completely compatible with the current bitmask approach for roles, but it also provides a simple and fast way to control administrative management of privileges in the system. Both user level and admin level roles can use the bitmask and are not limited to 1D heirarchy, but they are also compatible with IDAM privilege management.

Let me put it a different way. Think about how you'd design the code for every forum system ever. The forum has regular users with different roles, and a set of admin users. There are moderators, administrators, super admins, group admins, forum admins etc. Each of those admin users may set roles for the part of the forum they manage - either an individual forum, group of forums, the site as a whole etc. 

Work out how you'd code that with PHP-Auth admin(), without a very costly and hard to maintain conditional iterator, with repeated DB queries, like my example.

Does that make sense?

**Comment by rgvy** [comment]
Gotcha..........

In this case, maybe it makes sense to harden things a bit on the application layer to avoid a full-on nested loop. Maybe instead of an API/Route for elevating any user by any other user, you'd have one for each user-store / use case. So some layer with code specifically for EDITORs to grant TRANSLATOR (for example). You could even use hasRole to determine specifically if that user can grant a role to another user. You could abstract code to check and grant roles, then implement with with specific role parameters for each use case.

**Comment by 32Blahs** [comment]
I think you'd still end up with a complex logic set - you'd need one logic flow for EDITOR granting TRANSLATOR, and EDITOR granting CONTRIBUTOR, and so on, exponentially increasing the logic required for every role (or exponentially increasing the number of roles, requiring "CAN-GRANT-TRANSLATOR" etc).

You'd also need to test hasRole()  against each, which has the costly db lookup. And finally in your code, you'd have to create a complex logic flow to offer an admin view that allows a user to actually grant the role to a user - I.e. how would you generate a select picker that lists all the roles an admin could grant a user, with only the existing core PHPAuth methods (not my extend role methods)

Conversely my suggestion a) is a simple if( <= ) check and b) easy to visually see which roles are "superior" and order them in a view programmatically.

Unless I've misunderstood your suggestion? Interesting discussions as always though!

**Comment by rgvy** [comment]
Sure is an interesting discussion! It's great to have this community where we can learn from each other!

I think a lot depends on some of the supporting layers an implementor builds that are beyond this framework. The way I've built my route handlers, it's not too difficult... But I've approached this framework as more of a platform framework and less of an application framework -- I've built extensive application layer logic atop these lower level functions.

Just out of curiosity, how does your solution handle the issue of an EDITOR being able to grant TRANSLATOR but not a CONSULTANT; while a DEVELOPER can grant CONSULTANT but not TRANSLATOR?

**Comment by 32Blahs** [comment]
Understood, and from your other posts where you pointed me at the framework I realize we're approaching the use of this lib differently. In my case I've already built my bespoke framework from scratch, I was looking for a light user authentication only lib to plug in that I can build on - that's how I ended up with this lib (instead of for example the heavy Panique, UserSpice etc).

So from my point of view, I'm aiming for PHPAuth (and my extend) to provide 100% of the IDAM / RBAC core in non specific functionality, and I have a further class that sits on top of PHPAuth which wraps all my app specific logic and function. My app code then uses my class, so the IDAM (and PHPAuth) are completely abstracted.

Ref your question, you're right that my solution doesn't and can't handle that. All my solution can do is provide an easy way of controlling role granting/preventing privilege escalation using the current PHPAuth model of a non linear bitmask. 

To achieve what you mentioned requires a proper group and user directory solution, similar to LDAP, where rights can be granted against objects (not activities, like current model). To do this would require changing the role system to use DB tables and a directory structure - that's why I mentioned moving it all to the DB in my original post. 

I think a full directory solution is too complex for what the developers want to achieve with PHPAuth though. If you want that kind of functionality you'll need a heavier framework like User Cake/Spice etc, rather than a drop in lib like PHPAuth. At minimum you'll need to create lookup tables with guids that correlate objects to ACLs, with a set of standardized actions per object type and a set of methods that control/report whether a given object can take a given action on another object.

I'll have a think about it though, there may be an easier way to get 90% of the way there without heavy code. However any step towards implementing this will inherently break the current role approach, which is why I made the original suggestion as it's as far as we can go without really breaking too much.

**Comment by ocram** [comment]
@rgvy Thank you so much again!

@32Blahs I really think all this is just a misunderstanding and this library's role management simply works different from what you expected.

You're repeatedly talking about elevation of privileges, which is possible if (and only if) your application code allows it. Apart from that, and contrary to what you said, this library is not "vulnerable" to anything, at least not something you mentioned here.

You're just assuming an implicit hierarchy in the role management, which some implementations have, but this library does not. Simply put, no role is "higher" or "superior" to any other role. It's really as simple as that.

And then, as @rgvy put it:

> the framework is leaving it entirely up to the application layer (rather than the framework layer) to determine how to utilize any or all roles.

Regarding your description of the proposal:

> My suggestion doesn't limit anyone to a 1D heirarchy. It's completely compatible with the current bitmask approach for roles, but it also provides a simple and fast way to control administrative management of privileges in the system.

If that was really the case, I'd love to incorporate the changes into this library. But it obviously isn't.

> All my method does is require higher privileges to have higher values

See, this is not possible, because there is no notion of one role being higher than another one. You have to encode all that in your application-level code, and it *can* be done, quite easily even.

If you really can't come to terms with the role management included in this library, or if you decide that you really need something else, remember that you can simply leave out that part of the library and implement role management yourself or use another implementation. The management of roles and groups is really just a tiny part of this library and has been added only recently for cases where a simple but effective separation of privileges is required.

**Comment by rgvy** [comment]
@32Blahs, I can add that @ocram has actually provided documentation of a way to override the default role enumeration. See "Custom role names" in the docs...

**Comment by 32Blahs** [comment]
ocram, I think you're still not quite understanding what I'm saying. With the provision of the admin() interface, there is no separation of privilege for any user role that can call an admin() method unless you write complex logic into the app layer for actions that should be handled at the PHPAuth layer.

>  there is no notion of one role being higher than another one

And that's true, as long as roles are only used for controlling actions at the app layer. But as soon as you provide access to the admin interface for certain roles, such as Administrator, the hierarchy explicitly exists and PHPAuth should prevent users granting roles of greater privilege than they already have. 

It's simple to solve, by separating and ordering roles with admin() access by const value. That enables a simple check for "level of privilege" whilst also absolutely not affecting the bitmask approach for any role.

I don't seem to be able to explain this properly, so never mind.

**Comment by rgvy** [comment]
@32Blahs I think you just said exactly why we are not connecting on this issue.
> as long as roles are only used for controlling actions at the app layer
To me, this is the appropriate place to make the separation. Logic in this layer would prevent certain roles from reaching the `auth->admin()` interface...

**Comment by ocram** [comment]
> I think you're still not quite understanding what I'm saying.

I do! I just do not agree with all the conclusions or proposed solutions.

> With the provision of the admin() interface, there is no separation of privilege for any user role that can call an admin() method unless you write complex logic into the app layer for actions that should be handled at the PHPAuth layer.

Well, no role can automatically access the `admin()` interface. It's up to you to grant access to that interface for individual users or certain roles. And if you do that, of course you are also responsible for controlling that access which you granted. Again, there are no "admin" roles which can access that interface and "other" roles which cannot. So there's no point in dividing and ordering the roles as you suggested.

> And that's true, as long as roles are only used for controlling actions at the app layer. But as soon as you provide access to the admin interface for certain roles, such as Administrator, the hierarchy explicitly exists and PHPAuth should prevent users granting roles of greater privilege than they already have.

No, even then, the statement that there is no (implicit or explicit) hierarchy holds true.

> It's simple to solve, by separating and ordering roles with admin() access by const value.

See above, there are no such roles! *You* may grant such access to certain roles, but then *you* are also the one who needs to manage that access.
