### ISSUE TITLE
How does the testing work? I have a draft PostgreSQL schema that I'd like to test...

### ISSUE THREAD

**Issue by c5creative** [delight-im/PHP-Auth#57]
Greetings,

I looked at `delight-im/auth/tests/index.php`  and was wondering if there are instructions on how to run the test and what to expect? 

I gave it a try, using my connection params and I got a whole lot of markup. Not sure what it's supposed to mean.

As the title indicates, I created a PostgreSQL schema, that I'd like to contribute to the project, but obviously testing would be nice. 

Cheers,
JP

**Comment by ocram** [comment]
First, thanks a lot for your effort of preparing a PostgreSQL schema that you’re willing to contribute. That is very much appreciated!

Regarding the testing that you’d like to do, I have to say that the tests in `tests/index.php` are unfortunately no automated tests that you can run at once but manual tests that you have to run interactively in your web browser. They consist of forms and responses for all important features of the library. So you should point your web browser to that `index.php` file and view the rendered HTML.

Hope that helps!

**Comment by c5creative** [comment]
(sorry for the delay in my reply, I must have missed the email)

That is certainly helpful and I will do so. I have a schema, which seems to work just fine so far.  I ported it from the mySQL schema, but would like to add additional constraints (mainly foreign keys), so in order to maintain "parity" with your existing SQL setup, I will have the additional constraints as optional. Would that be OK?

**Comment by ocram** [comment]
No problem!

If you could move the foreign keys (and perhaps other constraints) all behind the required stuff, and mark with a comment that these are optional, that would be perfect.

**Comment by c5creative** [comment]
Sounds good :) I'll set up a pull request once it's tested. Cheers!
