### ISSUE TITLE
Is Multi Authentication Supported

### ISSUE THREAD

**Issue by peterson-umoke** [delight-im/PHP-Auth#62]
@Cosmologist ,Good day, Please i intend to use this library for a very large project... but i would like to know if i can check against multiple tables, in order words, say i am designing an e-commerce system, all admins have different levels, that requires a role authentication system, but the customers and the admins cannot share the same table structure, as such they need their own authentication procedures for the login, logout, register, please does your library support multi-authentication?

**Comment by Cosmologist** [comment]
Hello, @peterson-umoke, i'm not project maintainer, ask @ocram

**Comment by ocram** [comment]
> but i would like to know if i can check against multiple tables

Only if you use multiple instances of this library side by side. A single instance always operates on a single set of tables only.

> but the customers and the admins cannot share the same table structure

I don’t see if that’s really necessary, but if those are your project’s requirements, okay.

> they need their own authentication procedures for the login, logout, register

That would definitely two instances used side by side.

By the way, operating multiple instances simultaneously would probably require additional changes. What I can think of right now is that every usage of the session field names would have to be prefixed with some unique value for each of the instances: https://github.com/delight-im/PHP-Auth/blob/8fecb86f15b94ae5a9a9cea8712cf080b7ac6064/src/Auth.php#L24-L30

I’m not sure yet if other changes would be necessary, but can currently not think of any.

Hope that helps!

**Comment by peterson-umoke** [comment]
> I don’t see if that’s really necessary, but if those are your project’s requirements, okay
If you would suggest another way.... what do you have in mind ?

**Comment by ocram** [comment]
Why not? That’s what they are for. Depends on your implementation and usage of the roles, of course.

**Comment by peterson-umoke** [comment]
Thanks for your quick response. Get back to you if it works.
