### ISSUE TITLE
OrientDB support

### ISSUE THREAD

**Issue by tolgaulas** [delight-im/PHP-Auth#66]
I respect the comfort of PDO but I plan OrientDB (yet no PDO support); it sounds schizoid to have both.  Should I start another project based on you or should I fork?

**Comment by ocram** [comment]
Thanks!

We don’t see this project embrace a non-PDO database in the near future. Apart from that, we don’t see any distinct advantage for NoSQL or graph databases for the purposes of this library.

So please feel free to develop your own version based on this library.
