### ISSUE TITLE
Re-sync account properties to session

### ISSUE THREAD

**Issue by ocram** [delight-im/PHP-Auth#67]
The following four account properties may be changed remotely – either by a client in another session for the same account, or by an administrator:

```
email
username
status
roles_mask
```

During the lifetime of a session, these properties should regularly be fetched from their authoritative source in the database and synchronized back to the session. This should happen after a defined interval, e.g. every 5 minutes, which may also be configurable. The following fields in the session should be affected:

```
$_SESSION[UserManager::SESSION_FIELD_EMAIL]
$_SESSION[UserManager::SESSION_FIELD_USERNAME]
$_SESSION[UserManager::SESSION_FIELD_STATUS]
$_SESSION[UserManager::SESSION_FIELD_ROLES]
```

Additionally, a new flag should be introduced that is stored in a new column (and table) in the database. It will hold the information whether all sessions for a given account (except for *one* session, optionally) must perform a logout. This will allow for remote logouts and for revoking any (other) open sessions for an account as an additional security instrument that can be offered to users.

**Comment by acodispo** [comment]
@ocram I was about to post an issue along the lines of "newly added roles do not show up without logout/login", but I think that's because of this issue.

For instance, I can log in, add or remove a role via my admin interface. But my menu options (which are determined by what roles a user has) remain the same until I've logged out and logged back in.

Is my understanding correct?

Thanks!

**Comment by ocram** [comment]
@acodispo Exactly. And this issue here is about solving that problem by regularly checking the authoritative information on the server again.

You could do this on every single request (which means at least one additional database query per request), but for most people, “every 5 minutes” or at least “every 60 seconds” should be sufficient. With a configurable interval, we will have a solution that works for everybody.

**Comment by acodispo** [comment]
@ocram That's what I figured! Thanks! I'll keep an eye on this thread.

**Comment by akwatra** [comment]
if we have to sync with db, then why not try with [https://github.com/phpauth/phpauth](url)

I tried with that as this is good, only with email login, not with a username.  East pdo debugging than this one.

**Comment by ocram** [comment]
With regard to a user’s email address, username, status, and list of roles, this is supported now and turned on by default.

Implemented in:

 * https://github.com/delight-im/PHP-Auth/commit/21341d3c185928fe5f92ce04484c9a9b648fc4c8
 * https://github.com/delight-im/PHP-Auth/commit/89e99d727dbaa3955b5b49dd9d1538307314033a

The support for remote logouts will be tracked here: https://github.com/delight-im/PHP-Auth/issues/85
