### ISSUE TITLE
Database Error when Trying to Register User

### ISSUE THREAD

**Issue by nickian** [delight-im/PHP-Auth#71]
I am getting a database error when trying to use this library and trying to register a user. I'm not sure why because I've successfully used it this same way in other projects. Any idea what's happening here? It seems like it's not liking something about the database schema. I'm using MySQL 5.7.20.

I have the DB constant variables defined in a file that gets loaded before this one (as well as the composer autoload.php). I imported the MySQL schema and know that the user/pass/db name are all correct.

    $db = new PDO('mysql:dbname='.DB_NAME.';host='.DB_HOST.';charset=utf8mb4', DB_USER, DB_PASS);

    $auth = new \Delight\Auth\Auth($db);

    $userId = $auth->register('nick@domain.com', 'password', null);

This is the error I get in the Apache log:

```
PHP Fatal error:  Uncaught Delight\\Auth\\DatabaseError in /www/vendor/delight-im/auth/src/Auth.php:1221

Stack trace:

#0 /www/vendor/delight-im/auth/src/UserManager.php(99): Delight\\Auth\\Auth->throttle('register')

#1 /www/vendor/delight-im/auth/src/Auth.php(161): Delight\\Auth\\UserManager->createUserInternal(false, 'nick@domain.c...', 'password', NULL, NULL)

#2 /www/app.php(9): Delight\\Auth\\Auth->register('nick@domain.c...', 'password', NULL)

#3 /www/public/index.php(4): require_once('/www/app.php')

#4 {main}
 thrown in /www/vendor/delight-im/auth/src/Auth.php on line 1221
```

Thanks!

**Comment by ocram** [comment]
Thanks!

Can you please make sure that you’re actually using the version of the database schema that corresponds to the version of the library that you use? You can find your library version by running

```
$ composer show delight-im/auth
```

and checking the “versions” output. Alternatively, look into your `composer.lock` file manually.

You can find the correct database schema for that version by browsing the tagged version of this repository for your library version, e.g. like this:

```
https://github.com/delight-im/PHP-Auth/tree/v7.2.0/Database
```

If you updated the library to a new major version without updating the database schema, you might have missed some steps from the upgrade guide in the `Migration.md` file.

Last but not least, if you tell us your library version, we can check what the line numbers in the stack trace actually mean.

**Comment by ocram** [comment]
No problem, thanks!
