### ISSUE TITLE
Reset Password Failing on deleteRememberDirective

### ISSUE THREAD

**Issue by UrbanwarfareStudios** [delight-im/PHP-Auth#74]
On line 1178 of Auth.php it appears the resetPassword does not get past this point:

`1178: $this->deleteRememberDirective($resetData['user']);`

Does anyone else get this problem?

**Comment by ocram** [comment]
Thanks!

 1. What does it mean exactly that it “does not get past this point”? What problem does occur? Does it throw an exception? Can you share the stack trace? In what way does the library work different than you expected?
 1. What database are you using? MySQL or SQLite? Can you specify the version?
 1. Which version of this library are you using? Running

    ```
    $ composer show delight-im/auth
    ```

    will tell you. Is it the latest version?

 1. Does the version of the database schema that you imported match your version of this library?

**Comment by UrbanwarfareStudios** [comment]
Hi,

Please accept my apologies for the delay I was being chased out of the office on Friday night :)
I have done some further investigating and this is what is happening:

The function deleteRememberDirective calls the function setRememberCookie which is throwing a HeadersAlreadySentError - but this error isn't being caught or handled anywhere in the code for the reset etc so it kills off the rest of the code, even though the reset itself is successful.

I have resolved my issue by moving my code higher up the script (not that I was aware that I was already sending anything to the headers at the stage it was originally). It might be worth mentioning that this code is sensitive to such things?

I am using MySQL and I started using this on Thursday so it should be the latest version?

**Comment by ocram** [comment]
Thanks a lot for debugging this and sharing your solution!

> The function deleteRememberDirective calls the function setRememberCookie which is throwing a HeadersAlreadySentError - but this error isn't being caught or handled anywhere in the code for the reset etc so it kills off the rest of the code, even though the reset itself is successful.

Glad to hear that everything is working as expected then. The `HeadersAlreadySentError` is intentionally not caught anywhere, so that breaks your wrong code and alerts you in the logs.

> I have resolved my issue by moving my code higher up the script (not that I was aware that I was already sending anything to the headers at the stage it was originally).

Exactly, that’s the correct solution.

> It might be worth mentioning that this code is sensitive to such things?

That’s actually what the `HeadersAlreadySentError` was for. Didn’t that error appear in your stack trace?

> I am using MySQL and I started using this on Thursday so it should be the latest version?

Yes, everything should be fine with the versions then.
