### ISSUE TITLE
Function to list all roles a users has

### ISSUE THREAD

**Issue by jgriffin3** [delight-im/PHP-Auth#75]
I have been looking through the documentation and I am trying to find a way to display what role(s) a user has. I have only found how to check if a user has a certain role but not how to reveal what roles they have. Is there currently a way to do this?

**Comment by ocram** [comment]
Thanks for this request!

There’s indeed no way to retrieve this list directly, *yet*.

But you could combine the list of all roles and the feature to check whether a user has a certain role, which is already available, to achieve what you want, e.g. like this:

```php
/** @var \Delight\Auth\Auth $auth */

$roleReflection = new ReflectionClass(\Delight\Auth\Role::class);
$owned = [];

foreach ($roleReflection->getConstants() as $roleName => $roleValue) {
	if ($auth->hasRole($roleValue)) {
		$owned[$roleValue] = $roleName;
	}
}

return $owned;
```

Please tell me if this works. If there is demand for this feature, we could also add this solution (or a better one, if anybody has one) directly into the library.

Do you want this in the `Auth` interface (for users), or in the `Administration` interface (for admins), or both?

And do you need the (integer) values of these roles, or the names, or both?

**Comment by jgriffin3** [comment]
I haven’t had a chance to test out that code but ideally it would be something for the administration interface so that admins could easily display what roles a user has. For it to show the roles that it has it could either be the names or the integers for each roles or even both ints and names. 

I’ll try out the code in the next couple of days to see how it works out. Thanks!

**Comment by ocram** [comment]
This has been added now, both in the `Auth` interface for users and in the `Administration` interface for you and your team members.

Implemented in:

 * https://github.com/delight-im/PHP-Auth/commit/7d44158c3205b1532ff70ed8b4b362857c65ad8d
 * https://github.com/delight-im/PHP-Auth/commit/d834623954abfd9113121569d97256657dce1dc5
 * https://github.com/delight-im/PHP-Auth/commit/012577227a3cf0512db2b9e476b75d85c8744ef1
 * https://github.com/delight-im/PHP-Auth/commit/b0bf7647ce8f29c6b8ddace6400603ab17142c7c
 * https://github.com/delight-im/PHP-Auth/commit/13b58abebca709461d0428731a13097a773a8343
 * https://github.com/delight-im/PHP-Auth/commit/d9f9198b45545296cec68260688d85d3d2f49bb3
 * https://github.com/delight-im/PHP-Auth/commit/a2be4c61eed060d139003c807f81c93fe2b26c47
 * https://github.com/delight-im/PHP-Auth/commit/42a8c1616cd536a858fa370d2a00ec07ec19baed
