### ISSUE TITLE
Can't login - getting Warning: session_regenerate_id()

### ISSUE THREAD

**Issue by jonathancbatista** [delight-im/PHP-Auth#77]
Hi, I'm using PHP-Auth for dealing with users at my website. On my local server I'm getting this error when I try to login:

"Warning: session_regenerate_id(): Cannot regenerate session id - session is not active in [SOME PATH]/vendor/delight-im/cookie/src/Session.php on line 66"

Yesterday I've upgrade OSX to version 10.13.2, it's the unique thing that changed from yesterday to today. What am I missing?

**Comment by ocram** [comment]
Thanks for your report!

This is really strange. So it *did* work before the OS update? I see that your OS update may have updated Apache as well, but I don’t know about PHP. Can you check the PHP version that you’re running?

```bash
$ php --version
```

or

```php
\phpinfo();
```

The way that the `session_regenerate_id` function is called is the following:

 1. You sign in via either the [`Auth#login`](https://github.com/delight-im/PHP-Auth/blob/cd2ac479123285fb62a6379f3f92f38879ee44e0/src/Auth.php#L234) method or the [`Auth#loginWithUsername`](https://github.com/delight-im/PHP-Auth/blob/cd2ac479123285fb62a6379f3f92f38879ee44e0/src/Auth.php#L259) method.
 1. In each case, the method [`Auth#authenticateUserInternal`](https://github.com/delight-im/PHP-Auth/blob/cd2ac479123285fb62a6379f3f92f38879ee44e0/src/Auth.php#L944) is called [[1]](https://github.com/delight-im/PHP-Auth/blob/cd2ac479123285fb62a6379f3f92f38879ee44e0/src/Auth.php#L237)[[2]](https://github.com/delight-im/PHP-Auth/blob/cd2ac479123285fb62a6379f3f92f38879ee44e0/src/Auth.php#L262).
 1. On success, the [`Auth#onLoginSuccessful`](https://github.com/delight-im/PHP-Auth/blob/cd2ac479123285fb62a6379f3f92f38879ee44e0/src/Auth.php#L458) method is [called](https://github.com/delight-im/PHP-Auth/blob/cd2ac479123285fb62a6379f3f92f38879ee44e0/src/Auth.php#L985).
 1. That method, in turn, [calls](https://github.com/delight-im/PHP-Auth/blob/cd2ac479123285fb62a6379f3f92f38879ee44e0/src/Auth.php#L471) the [`UserManager#onLoginSuccessful`](https://github.com/delight-im/PHP-Auth/blob/cd2ac479123285fb62a6379f3f92f38879ee44e0/src/UserManager.php#L196) method.
 1. There, the method [`Session::regenerate`](https://github.com/delight-im/PHP-Cookie/blob/bb51b1fe4377e94b73239bd2cb1b6fa45b0cfa0e/src/Session.php#L64) from our cookie library is [called](https://github.com/delight-im/PHP-Auth/blob/cd2ac479123285fb62a6379f3f92f38879ee44e0/src/UserManager.php#L198).
 1. Finally, PHP’s `session_regenerate_id` method is [called](https://github.com/delight-im/PHP-Cookie/blob/bb51b1fe4377e94b73239bd2cb1b6fa45b0cfa0e/src/Session.php#L66) where your error message states that no session is active at that point.

However, right in the [`Auth` constructor](https://github.com/delight-im/PHP-Auth/blob/cd2ac479123285fb62a6379f3f92f38879ee44e0/src/Auth.php#L40), the method [`Auth#initSession`](https://github.com/delight-im/PHP-Auth/blob/cd2ac479123285fb62a6379f3f92f38879ee44e0/src/Auth.php#L54) is [called](https://github.com/delight-im/PHP-Auth/blob/cd2ac479123285fb62a6379f3f92f38879ee44e0/src/Auth.php#L47) where [`Session::start`](https://github.com/delight-im/PHP-Cookie/blob/bb51b1fe4377e94b73239bd2cb1b6fa45b0cfa0e/src/Session.php#L29) from our cookie library is [called](https://github.com/delight-im/PHP-Auth/blob/cd2ac479123285fb62a6379f3f92f38879ee44e0/src/Auth.php#L63). There, the session is started as usual by [calling](https://github.com/delight-im/PHP-Cookie/blob/bb51b1fe4377e94b73239bd2cb1b6fa45b0cfa0e/src/Session.php#L31) PHP’s `session_start` function.

What that means is that there should really be no point where we try to re-generate the session ID while the session itself has not been started.

Can you check why your session might not be started correctly? A good start may be going into `vendor/delight-im/auth/src/Auth.php` and checking if it makes a difference if you *temporarily* remove the `@` in front of the call to the `Session::start` method. With that change, maybe you’ll be seeing new warnings that are helpful.

**Comment by jonathancbatista** [comment]
Hey!
I found the problem! It's really linked to system upgrade. 
On OSX upgrade my http.conf was replaced, luckily the previous one was saved. Comparing the two files I found that apache was running at _www user, which was no permission to change files where my local websites are stored. Therefore PHP couldn't start the session. 

I've changed the Apache user and everything is working now. Thank you!

**Comment by ocram** [comment]
That makes sense, thank you!

As I said, an update for the Apache HTTP Server was included in your OS update. So that’s why the `http.conf` was modified.

As a general note, perhaps you shouldn’t modify the `http.conf` directly but rather put your custom configuration in some other file to avoid it being overwritten. There are alternatives.
