### ISSUE TITLE
Are user statuses in use?

### ISSUE THREAD

**Issue by Adifmac** [delight-im/PHP-Auth#79]
Noticed Status class (Status.php), however it is not documented anywhere.
Changing a user 'status' has no effect - a 'banned' user can login just the same. 
Am I missing anything?

**Comment by tomnuss** [comment]
In the readme the status is documented. You can check a banned user with the following (as explained in the readme):
`if ($auth->isBanned()) { }`

**Comment by ocram** [comment]
@tomnuss Thanks for helping!

@Adifmac It’s exactly as @tomnuss has explained.

If you detect that a user is banned, you may choose to cancel the current request, and perhaps log the user out immediately.

It would be trivial for this library to disallow logins by banned users, of course. But *for now*, in the name of flexibility and to support versatile use cases, the effect of the individual states is left entirely up to the user of this library.
