### ISSUE TITLE
Login remembered

### ISSUE THREAD

**Issue by dijokl** [delight-im/PHP-Auth#8]
Hallo und frohes neues Jahr für euch!
Ich versuchs mal auf deutsch, sorry.
Ich denke, dass es ein Fehlverhalten gibt, bei der Angabe des zweiten Parameters im Konstruktor.
Oder ich habs noch nicht verstanden...
Also wenn das ausgeführt wird:
$auth = new \Delight\Auth\Auth($db, true);
$auth->login($_POST['email'], $_POST['password'], null);

dann erzeugt später komischerweise $auth->check() den Wert false.
Obwohl man doch mindestens bis zum Schließen des Browsers angemeldet sein müsste.
Lediglich die Session-Variable "auth-remember" ist verfügbar!?
Wenn beim instanzieren "true" weggelassen wird, funktioniert es wie erwartet.
Das passiert sowohl lokal (XAMPP, PHP5.6) als auch bei STRATO-Hosting (SSL, PHP5.6)
Am Ende will ich eigentlich nur, dass ohne Zeitvorgabe die Session bei Beenden des Browsers zu Ende ist, also automatisch ausgeloggt wird. Ich bekomme es nicht hin ...
Can you help? ;-)

**Comment by ocram** [comment]
Frohes neues Jahr!

Kein Problem und vielen Dank für das Feedback :)

Die Parameter des Konstruktors haben ja erst einmal gar nichts damit zu tun, ob der Login dauerhaft ist ("remember me") oder nur bis zum Ende der Browser-Session. Das ist mit dem Argument `null` im Aufruf von `login` aber schon richtig gemacht.

Der zweite Parameter des Konstruktors kontrolliert nur das Flag `secure` für Session-Cookies. Mit dem Flag auf `false` (der Standard ohne Angabe des Parameters) werden Session-Cookies sowohl über HTTP als auch über HTTPS gesendet und empfangen, was die maximale Kompatibilität bietet. Das scheint ja zu funktionieren.

Wenn das Flag aber über den Parameter auf `true` gesetzt wird, dann werden die Session-Cookies eben *nur* über HTTPS gesendet und empfangen. Das Problem wäre dann also erklärt, falls entweder beim Login oder später eine Seite über einfaches HTTP angefragt wird.

Hilft das?

**Comment by dijokl** [comment]
Wieder einmal schön schnell geantwortet, Danke!
Aber irgendwie bin ich noch nicht ganz zufrieden mit der Antwort, weil ich immer noch nicht weiß, warum 
$auth->check() False zurück gibt.
U.a. getestet mit "test.php", welches dem Package beiliegt.
Und wie gesagt, auf dem SSL-Host-Server bleibe ich nicht eingeloggt, wenn ich bei der Login-Prcedure den Parameter rememberDuration mit Null angebe. Alle Rückgaben ergeben direkt nach Aufruf: ok, eingeloggt. Aber ein weiterer Refresh ergibt False bei $auth->check(). Bzw. weitere Aufrufe von getUserId, GetUsername oder getEmail ergeben Nullwerte ...
Vielleicht doch eine Idee?

**Comment by ocram** [comment]
Laut der Beschreibung im ersten Kommentar ging es ja um den Parameter für den *Konstruktor* (der das Flag `secure` setzt oder eben nicht) und nicht um den Parameter für die Methode `login` (der für einen dauerhaften Login sorgt oder eben nicht):

> Wenn beim instanzieren "true" weggelassen wird, funktioniert es wie erwartet.

Welcher der Parameter jetzt das Problem auslöst, muss schon klar sein, und ansonsten muss die Fehlerquelle eben erst noch isoliert werden. Das hier widerspricht der ersten Beschreibung ja:

> Und wie gesagt, auf dem SSL-Host-Server bleibe ich nicht eingeloggt, wenn ich bei der Login-Prcedure den Parameter rememberDuration mit Null angebe.

*Alle* Methoden geben Werte für einen nicht einloggten Benutzer zurück, wenn das Session-Cookie fehlt. Denn dann kann die Session, in der der Benutzer sich eingeloggt hat, natürlich nicht fortgesetzt werden.
