### ISSUE TITLE
Adding foreign keys

### ISSUE THREAD

**Issue by chibicitiberiu** [delight-im/PHP-Auth#86]
Advantages:
* added consistency checks
* some operations (such as update and delete) can be cascaded. 

Disadvantages:
* there can be some performance degradation (i.e. the DBMS needs to check that the referenced record exists), but mostly to inserts/updates
* lack of support from database storage systems
    * SQLite - has support, but disabled by default; also depends on build configuration.
    * MySQL/MariaDB - the MyISAM storage engine doesn't support them
    * PostgreSQL - full support

**Comment by ocram** [comment]
Thanks!

We definitely want maximum compatibility, and as much portability between the three database systems as can reasonably be achieved without forgoing useful improvements.

Could you suggest some foreign key constraints that would make sense?

**Comment by chibicitiberiu** [comment]
Looking at the schema, this is what I found so far. Please correct me if I missed one, or if I'm wrong. I am not very familiar with how the library works.

    users_confirmations.user_id -> users.id
    users_confirmations.email - is this the same as users.email?
    users_remembered.user -> users.id
    users_resets.user -> users.id

**Comment by ocram** [comment]
Thanks, I agree with those relations. Though `users_confirmations.email` is indeed not (necessarily) the same as `users.email` because it may be used to store and set a new email address when a user chose to change their address using `Auth#changeEmail`.

So that leaves us with only the following three relations:

```
users_confirmations.user_id -> users.id
users_remembered.user -> users.id
users_resets.user -> users.id
```

And these are exactly the tables where we’ll enable garbage collection soon, as documented in https://github.com/delight-im/PHP-Auth/issues/68. That’s why I think the advantage of foreign keys is not really significant for this library.

**Comment by ocram** [comment]
For now, this is not worth it. We might revisit this later.

**Comment by dcdeiv** [comment]
+1 for this feature because it will make much faster and easier to add other user info in a separate table e.g. (first name, last name, birth, and so on)

**Comment by ocram** [comment]
@dcdeiv Thanks! Could you name the specific foreign keys that you would like to see added? And, more importantly, is there anything that prevents you from adding these keys yourself, connecting the tables of this library with your custom tables?

**Comment by ocram** [comment]
@dcdeiv Thank you!

Converting all tables used by this library from MyISAM to InnoDB is something we definitely want to do in the future and which we fully support today. If running

```sql
ALTER TABLE my_table ENGINE = InnoDB;
```

is not enough or triggers any problems, please report this here and we will fix what is needed. As soon as the tables have been converted to the new storage engine, we will also add those three foreign keys mentioned above.

So, for now, please just go ahead and convert all of this library’s tables to InnoDB, then add the three foreign keys agreed upon above. All that will be supported by us.

You should then be free to add your custom foreign keys for relations to your custom tables. But we will obviously not support that. Anyway, it should be easy to add those custom foreign keys without breaking this library.
