### ISSUE TITLE
Warning in PHP 7.x

### ISSUE THREAD

**Issue by Skyost** [delight-im/PHP-Auth#87]
Hey,

I'm having a warning while running your library in PHP 7.x (and when I'm using admin to change one's email) :

`<b>Warning</b>:  count(): Parameter must be an array or an object that implements Countable in <b>C:\[...]\delight-im\auth\src\Administration.php</b> on line <b>513</b><br />`

Great library btw ! 👍

**Comment by ocram** [comment]
Thanks for reporting this and for your appreciation!

It seems the line in question is the following one: https://github.com/delight-im/PHP-Auth/blob/e7e174b05d63e6e62fdd8f70a8824c9a2ff4363c/src/Administration.php#L513

So it seems you’re trying to sign in as a certain user, i.e. impersonate that user. Is this correct? This is probably the step before you actually want to change their email address.

Could it be that the user in question does not exist? That means, can you still re-produce the problem when signing in as a user that definitely exists?

By the way, in the title you wrote `7.x` while you wrote `7.3` in the message, but I guess that doesn’t make any difference here.

**Comment by Skyost** [comment]
Oops yeah, the error is from me ! I thought it was an error from the library so this is why I reported it. Thank you !

**Comment by ocram** [comment]
Well, no. I guess you were right about this being the library.

Did you indeed try to sign in as some user that does not exist?

In that case, the library should certainly not output such a warning but a proper, well-defined and documented exception.

**Comment by Skyost** [comment]
Yes that was (unintentionally) what I was trying to do.

While I am at it, is there a way to have a list of users ?

**Comment by ocram** [comment]
Your PHP version did indeed make the difference. The behavior of the `count` function with an argument of `null` changed in PHP 7.2 [[1]](https://wiki.php.net/rfc/counting_non_countables) [[2]](http://php.net/manual/en/migration72.incompatible.php) and started triggering a warning.

The issue should have been fixed now and you should see the warning disappear if you update to the latest version of this library.

Thanks for bringing this to our attention!

(Regarding your question about querying users: No, that’s not currently included. We don’t know how you want to query, what filters to apply, whether to return an associative array, an array of objects or an array of objects, what columns to return, and which other tables to possibly join. So we think this is better done in your own code, which should be trivial.)

**Comment by Skyost** [comment]
Thanks for your answers !
