### ISSUE TITLE
How to set status of users?

### ISSUE THREAD

**Issue by disneian** [delight-im/PHP-Auth#94]
Is it possible to update/set the status (locked, suspended, pending review etc) of a user by the admin? I couldn't find a method to do so.

**Comment by ocram** [comment]
Thanks for your feedback!

You are right, there’s indeed no method in the `Administration` interface yet that allows you to do that. Sorry! We should definitely add this in the future.

Until then, changing the status should still be as easy as executing the custom SQL query

```sql
UPDATE users SET status = ? WHERE id = ?
```

with the first parameter being one of the values

```php
\Delight\Auth\Status::NORMAL;
\Delight\Auth\Status::ARCHIVED;
\Delight\Auth\Status::BANNED;
\Delight\Auth\Status::LOCKED;
\Delight\Auth\Status::PENDING_REVIEW;
\Delight\Auth\Status::SUSPENDED;
```

and the second parameter being the user ID, which can be accessed like this:

```php
$auth->getUserId();
```

Hope that helps!

**Comment by disneian** [comment]
Thanks

**Comment by ponasromas** [comment]
Bumping this old thread and vouching for function that allows user status manipulation :) . Thank you Ocram!
