### ISSUE TITLE
[QUESTION] Disconnect an user

### ISSUE THREAD

**Issue by Skyost** [delight-im/PHP-Auth#95]
Hi,

I want to disconnect an user (via an interface). Therefore, I'm using the following code :

```php
$email = 'user@mail.com';
$currentEmail = $auth -> getEmail();

$admin = $auth -> admin();
$admin -> logInAsUserByEmail($email);
$auth -> logOutEverywhere();
$admin -> logInAsUserByEmail($currentEmail);
```

But the user still getting deconnected, even when I'm using `$admin -> logInAsUserByEmail($currentEmail);` after the log out. So I just want to know what I'm doing wrong.

Thanks for your help !

**Comment by ocram** [comment]
What are you trying to do exactly? Saying you want to “disconnect” a user, do you refer to the global logout on all devices?

So you’re logged in as user A (perhaps your admin account), and then want to *temporarily* sign in as user B (`user@mail.com`) to log them out on all devices. Afterwards, you want to sign back in to the first account, user A. Is this what you’re trying to do?

What’s the problem? What’s going wrong with that process? Is the wrong user logged out? Or are both logged out?

**Comment by Skyost** [comment]
Yes, that's what I am trying to do and both users are logged out. In fact, I'm trying to create an user editing interface, where the admin can edit some users properties (eg. name, roles, ...).

After everything is edited, I need to log out the edited user, otherwise he is not going to see the changes immediatly.

**Comment by ocram** [comment]
Well, an important point to consider is that your users will see the effects of the remote logout just as early or as late as they would see any other changes to their account (e.g. roles).

Both actions are propagated to other sessions by the same mechanism, which is controlled by the `$sessionResyncInterval` parameter of the `Auth` constructor, as outlined in the documentation. So, after all, you might not even need the global logout, just a local one using `$auth->logOut()`.

We don’t know of any problems with calling the two methods

```php
$auth->logOutEverywhere();
$auth->admin()->logInAsUserById($myId);
```

in that order in direct succession. Just make sure that you call these before any actual HTML content is output, i.e. before the HTTP headers are sent to the user. That being said, calling

```php
$auth->admin()->logInAsUserById($myId);
```

alone should still be enough.

Does that help?

**Comment by Skyost** [comment]
Oh okay, I understand. That's fine for me, thanks for your help !
