### ISSUE TITLE
[QUESTION] Oauth

### ISSUE THREAD

**Issue by disneian** [delight-im/PHP-Auth#96]
Thank you for the package. This makes managing user login so much more easier and secure. I would like to know if there are any way to incorporate oauth to the system? In particular, I'm looking for a way to authenticate and authorize the user to use an api, and I like to implement some authentication method like oauth or a jwt token for the api to validate the request. Seeing that the package already done the authentication part, is there a way to generate a validation token after a user has log in?

**Comment by ocram** [comment]
Thanks for your appreciation!

Something like OAuth is not part of this library at the moment and we don’t have any plans to add support for it, at least for now. Sorry!

On the other hand, some components that can be used for API authentication and that play well with the rest of this library would be really useful. Your main point is probably that you want authentication without cookies for your API, right? Cookies are probably the only thing that prevents you from using this library for your API as it is. The rest can be used just fine, replacing the HTML forms with JSON requests and responses, for example.

You could just create some tokens yourself and store them in the database in a new table. Or you could [make use of JWT tokens](https://github.com/delight-im/PHP-Auth/issues/76#issuecomment-359261910). Apart from that, you’ll need some other library or custom implementation for anything else, unfortunately.
