### ISSUE TITLE
Fatal error: Uncaught Delight\Auth\TooManyRequestsException

### ISSUE THREAD

**Issue by Div-Man** [delight-im/PHP-Auth#98]
I tried to register many times, the error TooManyRequestsException worked, then I cleaned it and now writes

`Fatal error: Uncaught Delight\Auth\TooManyRequestsException in C:\OSPanel\domains\crud\vendor\delight-im\auth\src\Auth.php:1759 Stack trace: #0 C:\OSPanel\domains\crud\vendor\delight-im\auth\src\Auth.php(231): Delight\Auth\Auth->throttle(Array, 1, 43200, 5, true) #1 C:\OSPanel\domains\crud\app\controllers\RegisterController.php(44): Delight\Auth\Auth->register('', '', '', Object(Closure)) #2 [internal function]: App\controllers\RegisterController->register() #3 C:\OSPanel\domains\crud\vendor\php-di\invoker\src\Invoker.php(82): call_user_func_array(Array, Array) #4 C:\OSPanel\domains\crud\vendor\php-di\php-di\src\Container.php(269): Invoker\Invoker->call(Array, Array) #5 C:\OSPanel\domains\crud\app\start.php(81): DI\Container->call(Array, Array) #6 C:\OSPanel\domains\crud\web\index.php(6): require('C:\\OSPanel\\doma...') #7 {main} thrown in C:\OSPanel\domains\crud\vendor\delight-im\auth\src\Auth.php on line 1759`

I do not know what to do.

 ```
  public function register()
    {
      try {
            $this->auth->register($_POST['email'], $_POST['password'], $_POST['username'], function ($selector, $token) {
            });

      }
           
        catch (\Delight\Auth\InvalidEmailException $e) {
            echo 'Введите email';
        }
        catch (\Delight\Auth\InvalidPasswordException $e) {
            echo 'Введите пароль';
        }
        catch (\Delight\Auth\UserAlreadyExistsException $e) {
            echo 'Пользователь с таким Email уже существует';
        }
       
         catch (\Delight\Auth\DuplicateUsernameException $e) {
            echo 'Пользователь с таким именем уже существует';
        }
      
        /*
        catch (\Delight\Auth\TooManyRequestsException $e) {
            echo 'Слишком много запросов, подождите некоторое время';
        }
         * 
         */
            
        
    }
```

If you do this, nothing is displayed and nothing is added to the database

```
  public function register()
    {
      try {
            $this->auth->register($_POST['email'], $_POST['password'], $_POST['username'], function ($selector, $token) {
            });

      }
           
        catch (\Delight\Auth\InvalidEmailException $e) {
            echo $e->getMessage();
        }
        catch (\Delight\Auth\InvalidPasswordException $e) {
             echo $e->getMessage();
        }
        catch (\Delight\Auth\UserAlreadyExistsException $e) {
             echo $e->getMessage();
        }
       
         catch (\Delight\Auth\DuplicateUsernameException $e) {
            echo $e->getMessage();
        }
      
        
        catch (\Delight\Auth\TooManyRequestsException $e) {
            echo $e->getMessage();
        }       
        
    }
```

**Comment by ocram** [comment]
How did you “clean it”?

Is commenting out the exception handler what you were referring to? You did this in the first code block. That does not work, of course. It will only let the error bubble up and emerge as a fatal error because it has not been handled.

The correct way to reset the counters for throttling is clearing the database table that keeps track of what to throttle:

```sql
TRUNCATE users_throttling;
```

Keep in mind that this will affect the throttling for *all* users and *any* action that is tracked.

During development, it might be more practical to disable throttling entirely, which is what the README suggests:

> During development, you may want to disable the request limiting or throttling performed by this library. To do so, pass `false` to the constructor as the fourth argument, which is named `$throttling`. The feature is enabled by default.

Hope that helps!

**Comment by Div-Man** [comment]
@ocram thanks, I'll try later
